"""
Anchor Point Model
Stores analogy bridges between new learning concepts and David's known domains.
Generated by the anchor service, validated/rejected by David.
"""
from sqlalchemy import Column, String, Text, DateTime, Float, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.base import Base
import uuid


class AnchorPoint(Base):
    """Analogy anchors connecting new concepts to known domains"""
    __tablename__ = "anchor_point"
    __table_args__ = {"extend_existing": True}

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("app_user.id", ondelete="CASCADE"), nullable=False)
    topic_id = Column(String, ForeignKey("learning_topic.id", ondelete="CASCADE"), nullable=False)

    # Anchor details
    anchor_concept = Column(String(500), nullable=False)  # The analogy concept
    anchor_domain = Column(String(255), nullable=False)  # Which known domain it maps to
    bridge_description = Column(Text, nullable=True)  # How the analogy works
    confidence = Column(Float, default=0.5)  # 0.0 to 1.0
    validated = Column(Boolean, default=False)  # David confirmed this works
    rejected = Column(Boolean, default=False)  # David said this doesn't work

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", foreign_keys=[user_id])
    topic = relationship("LearningTopic", foreign_keys=[topic_id])

    def to_dict(self):
        return {
            "id": self.id,
            "user_id": self.user_id,
            "topic_id": self.topic_id,
            "anchor_concept": self.anchor_concept,
            "anchor_domain": self.anchor_domain,
            "bridge_description": self.bridge_description,
            "confidence": self.confidence,
            "validated": self.validated,
            "rejected": self.rejected,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
