"""Autonomous insight and activity tracking models."""
from sqlalchemy import Column, String, Text, DateTime, Integer, Float, Boolean
from sqlalchemy.sql import func
from app.db.base import Base
import uuid


class AutonomousInsight(Base):
    """Insights generated by Sara's autonomous background processes."""
    __tablename__ = "autonomous_insight"
    __table_args__ = {'extend_existing': True}

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, nullable=False)
    insight_type = Column(String, nullable=False)  # pattern, suggestion, summary, reminder, connection, analysis
    sweep_type = Column(String, nullable=False)  # quick_sweep, standard_sweep, digest_sweep
    priority_score = Column(Float, nullable=False)
    title = Column(String, nullable=False)
    message = Column(Text, nullable=False)
    action_suggestion = Column(String, nullable=True)  # JSON
    related_data = Column(Text, nullable=True)  # JSON
    surfaced_at = Column(DateTime, nullable=True)
    user_action = Column(String, nullable=True)  # dismissed, acted_on, saved, snoozed
    feedback_score = Column(Integer, nullable=True)  # -1, 0, 1
    generated_at = Column(DateTime, server_default=func.now())
    expires_at = Column(DateTime, nullable=True)


class InsightNudge(Base):
    """Nudges/notifications sent to user based on insights."""
    __tablename__ = "insight_nudge"
    __table_args__ = {'extend_existing': True}

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, nullable=False)
    insight_id = Column(String, nullable=False)
    delivery_method = Column(String, nullable=False)  # sprite_toast, sprite_badge, ntfy_push
    delivered_at = Column(DateTime, server_default=func.now())
    clicked = Column(Boolean, default=False)
    dismissed_at = Column(DateTime, nullable=True)
    action_taken = Column(String, nullable=True)  # reply, open, ignore


class ActivitySession(Base):
    """Track user activity sessions for autonomous behavior triggers."""
    __tablename__ = "activity_session"
    __table_args__ = {'extend_existing': True}

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, nullable=False)
    session_start = Column(DateTime, nullable=False)
    session_end = Column(DateTime, nullable=True)
    idle_duration = Column(Integer, default=0)  # milliseconds
    active_view = Column(String, nullable=True)
    interaction_count = Column(Integer, default=0)
    quick_sweep_triggered = Column(Boolean, default=False)
    standard_sweep_triggered = Column(Boolean, default=False)
    digest_sweep_triggered = Column(Boolean, default=False)
    insights_generated = Column(Integer, default=0)
    created_at = Column(DateTime, server_default=func.now())


class BackgroundSweep(Base):
    """Log of background sweep executions and their results."""
    __tablename__ = "background_sweep"
    __table_args__ = {'extend_existing': True}

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, nullable=False)
    sweep_type = Column(String, nullable=False)  # quick_sweep, standard_sweep, digest_sweep
    triggered_by = Column(String, nullable=False)  # idle_threshold, manual, scheduled
    execution_time_ms = Column(Integer, nullable=False)
    insights_generated = Column(Integer, default=0)
    errors_encountered = Column(Text, nullable=True)  # JSON array
    episodes_analyzed = Column(Integer, default=0)
    notes_analyzed = Column(Integer, default=0)
    patterns_found = Column(Text, nullable=True)  # JSON summary
    executed_at = Column(DateTime, server_default=func.now())
