/**
 * Adds the UIScene lifecycle required by apps built with the iOS 27 SDK.
 *
 * Expo SDK 54 still generates an AppDelegate that creates the React Native
 * window directly. This plugin keeps Expo's factory and subscriber behavior,
 * but moves window creation into a single-window scene delegate.
 */
const {
  withDangerousMod,
  withInfoPlist,
  withXcodeProject,
} = require('@expo/config-plugins')
const fs = require('fs')
const path = require('path')

const SWIFT_FILENAME = 'SaraSceneDelegate.swift'

const SWIFT_CONTENTS = `import Expo
import React
import UIKit

// Generated by withSaraSceneLifecycle. Edit the config plugin, not this file.
final class SaraSceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard
      let windowScene = scene as? UIWindowScene,
      let appDelegate,
      let factory = appDelegate.reactNativeFactory
    else {
      return
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    appDelegate.window = window

    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: nil
    )
    window.makeKeyAndVisible()

    if let urlContext = connectionOptions.urlContexts.first {
      DispatchQueue.main.async {
        _ = RCTLinkingManager.application(
          UIApplication.shared,
          open: urlContext.url,
          options: [:]
        )
      }
    }

    if let userActivity = connectionOptions.userActivities.first {
      DispatchQueue.main.async {
        _ = RCTLinkingManager.application(
          UIApplication.shared,
          continue: userActivity,
          restorationHandler: { _ in }
        )
      }
    }
  }

  func sceneDidBecomeActive(_ scene: UIScene) {
    appDelegate?.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    appDelegate?.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    appDelegate?.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    appDelegate?.applicationDidEnterBackground(UIApplication.shared)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    for context in URLContexts {
      _ = RCTLinkingManager.application(
        UIApplication.shared,
        open: context.url,
        options: [:]
      )
    }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    _ = RCTLinkingManager.application(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }
}
`

const LEGACY_WINDOW_SETUP = `#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif
`

const SCENE_CONFIGURATION = `  public func application(
    _ application: UIApplication,
    configurationForConnecting connectingSceneSession: UISceneSession,
    options: UIScene.ConnectionOptions
  ) -> UISceneConfiguration {
    let configuration = UISceneConfiguration(
      name: "Default Configuration",
      sessionRole: connectingSceneSession.role
    )
    configuration.delegateClass = SaraSceneDelegate.self
    return configuration
  }

`

const withSaraSceneLifecycle = (config) => {
  config = withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneClassName: 'UIWindowScene',
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SaraSceneDelegate',
          },
        ],
      },
    }
    return cfg
  })

  config = withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const projectName = cfg.modRequest.projectName
      const sourceRoot = path.join(cfg.modRequest.platformProjectRoot, projectName)
      const appDelegatePath = path.join(sourceRoot, 'AppDelegate.swift')
      const sceneDelegatePath = path.join(sourceRoot, SWIFT_FILENAME)

      fs.writeFileSync(sceneDelegatePath, SWIFT_CONTENTS, 'utf8')

      let appDelegate = fs.readFileSync(appDelegatePath, 'utf8')
      if (appDelegate.includes(LEGACY_WINDOW_SETUP)) {
        appDelegate = appDelegate.replace(LEGACY_WINDOW_SETUP, '')
      } else if (!appDelegate.includes('configurationForConnecting connectingSceneSession')) {
        throw new Error('Unable to locate Expo window setup in AppDelegate.swift')
      }

      if (!appDelegate.includes('configurationForConnecting connectingSceneSession')) {
        const marker = '  // Linking API\n'
        if (!appDelegate.includes(marker)) {
          throw new Error('Unable to locate AppDelegate linking marker')
        }
        appDelegate = appDelegate.replace(marker, SCENE_CONFIGURATION + marker)
      }

      fs.writeFileSync(appDelegatePath, appDelegate, 'utf8')
      return cfg
    },
  ])

  config = withXcodeProject(config, (cfg) => {
    const project = cfg.modResults
    const projectName = cfg.modRequest.projectName
    const relativePath = `${projectName}/${SWIFT_FILENAME}`

    if (!project.hasFile(relativePath)) {
      const target = project.getFirstTarget().uuid
      const group =
        project.findPBXGroupKey({ name: projectName }) ||
        project.getFirstProject().firstProject.mainGroup
      project.addSourceFile(relativePath, { target }, group)
    }

    return cfg
  })

  return config
}

module.exports = withSaraSceneLifecycle
