/**
 * withSaraAppIntents — Expo config plugin (P3, Siri).
 *
 * App Intents / AppShortcutsProvider must live in the MAIN app target for Siri to
 * surface "Ask Sara" with zero user setup (an extension is not enough). Expo's
 * managed prebuild doesn't add main-target Swift, so this plugin:
 *   1. writes SaraAppIntents.swift into ios/<App>/ during prebuild, and
 *   2. adds it to the main app target's Sources build phase.
 *
 * The intent opens sara://ask?q=<prompt>, which the JS deep-link handler turns
 * into a chat message.
 */
const { withXcodeProject, withDangerousMod } = require('@expo/config-plugins')
const fs = require('fs')
const path = require('path')

const SWIFT_FILENAME = 'SaraAppIntents.swift'

const SWIFT_CONTENTS = `import AppIntents
import Foundation

// Generated by withSaraAppIntents config plugin. Edit the plugin, not this file.

@available(iOS 16.0, *)
struct AskSaraIntent: AppIntent {
  static var title: LocalizedStringResource = "Ask Sara"
  static var description = IntentDescription("Ask Sara a question by voice.")
  static var openAppWhenRun: Bool = true

  @Parameter(title: "Question", requestValueDialog: "What do you want to ask Sara?")
  var prompt: String

  @MainActor
  func perform() async throws -> some IntentResult & OpensIntent {
    let encoded = prompt.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? ""
    let url = URL(string: "sara://ask?q=\\(encoded)") ?? URL(string: "sara://ask")!
    return .result(opensIntent: OpenURLIntent(url))
  }
}

@available(iOS 16.0, *)
struct SaraAppShortcuts: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
    AppShortcut(
      intent: AskSaraIntent(),
      phrases: [
        "Ask \\(.applicationName)",
        "Ask \\(.applicationName) a question",
        "Talk to \\(.applicationName)"
      ],
      shortTitle: "Ask Sara",
      systemImageName: "bubble.left.and.bubble.right.fill"
    )
  }
}
`

const withSaraAppIntents = (config) => {
  // 1. Drop the Swift file into the main app source folder.
  config = withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const projectName = cfg.modRequest.projectName
      const dest = path.join(cfg.modRequest.platformProjectRoot, projectName, SWIFT_FILENAME)
      fs.mkdirSync(path.dirname(dest), { recursive: true })
      fs.writeFileSync(dest, SWIFT_CONTENTS, 'utf8')
      return cfg
    },
  ])

  // 2. Register it with the main app target so it actually compiles.
  config = withXcodeProject(config, (cfg) => {
    const project = cfg.modResults
    const projectName = cfg.modRequest.projectName
    const relPath = `${projectName}/${SWIFT_FILENAME}`

    if (project.hasFile(relPath)) {
      return cfg
    }

    const target = project.getFirstTarget().uuid
    const group =
      project.findPBXGroupKey({ name: projectName }) ||
      project.getFirstProject().firstProject.mainGroup

    project.addSourceFile(relPath, { target }, group)
    return cfg
  })

  return config
}

module.exports = withSaraAppIntents
