#!/usr/bin/env python3
"""
Arc 3 scheduled_job inventory + cognition/plumbing classification
(SARA_ALIVE_BUILD_PLAN Arc 3.2, per David's 2026-07-29 design-first guidance).

Produces a markdown document — every enabled scheduled_job row, its
classify_job() heuristic class (sensor|maintenance|anchor|legacy_cognition|
unclassified, from app.services.scheduler_diet — SINGULAR_SARA_MASTER_PLAN
§C11), evidence (last_status/last_run_at/last_error/duration), and for
legacy_cognition rows a PROPOSED kernel.WakeReason mapping.

Read-only. Produces a document for review — does NOT disable, migrate, or
delete anything. Migration is a separate, later step per row, once this
document is approved (old job disabled-not-deleted -> kernel equivalent
verified live -> then deleted, matching the plan's write-freeze pattern).

Run:
  docker compose -f docker-compose.dev.yml exec -T backend \\
    python scripts/arc3_job_inventory.py --out /path/to/report.md
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

# Keyword -> proposed WakeReason for legacy_cognition rows. Same spirit as
# scheduler_diet's own heuristics: a starting point for human review, not
# an automatic mapping anything migrates on.
_WAKE_REASON_HINTS = [
    (("checkin", "check_in"), "CHECKIN"),
    (("anticipat",), "ANTICIPATION"),
    (("interocept", "self_audit", "self-audit", "health_status"), "INTEROCEPTION"),
    (("daemon",), "DAEMON_PROXY"),
    (("dream", "reflect", "consolidat"), "DAEMON_PROXY"),  # dreaming state, not ambient — flagged for review
    (("idle",), "SLEEP_PRESSURE"),
]


def _propose_wake_reason(job: dict) -> str:
    haystack = " ".join(str(job.get(k) or "") for k in
                         ("key", "display_name", "task_name", "category", "description")).lower()
    for hints, reason in _WAKE_REASON_HINTS:
        if any(h in haystack for h in hints):
            return reason
    return "PROMOTED_EVENT"  # generic default — needs human judgment


def build_report() -> str:
    from sqlalchemy import text
    from app.db.session import SessionLocal
    from app.services.scheduler_diet import classify_job

    db = SessionLocal()
    try:
        rows = db.execute(text("""
            SELECT key, display_name, description, category, task_name,
                   schedule_kind, cron_expr, interval_seconds, queue,
                   enabled, last_run_at, last_status, last_error, last_run_duration_ms
            FROM scheduled_job
            ORDER BY category, key
        """)).mappings().fetchall()
    finally:
        db.close()

    jobs = [dict(r) for r in rows]
    for j in jobs:
        j["singular_class"] = classify_job(j)

    enabled_jobs = [j for j in jobs if j["enabled"]]
    by_class: dict = {}
    for j in jobs:
        by_class.setdefault(j["singular_class"], []).append(j)

    lines = []
    lines.append("# Arc 3 scheduled_job inventory — cognition vs. plumbing")
    lines.append("")
    lines.append(f"Generated by `scripts/arc3_job_inventory.py`. Total rows: {len(jobs)} "
                 f"({len(enabled_jobs)} enabled). Read-only snapshot — nothing here has been "
                 f"migrated, disabled, or deleted.")
    lines.append("")
    lines.append("## Census")
    lines.append("")
    lines.append("| Class | Count | Meaning |")
    lines.append("|---|---|---|")
    meaning = {
        "legacy_cognition": "Candidate to fold into a kernel wake reason (ambient_turn)",
        "anchor": "Time-of-day anchor — maps directly to WakeReason.SCHEDULED_ANCHOR",
        "maintenance": "Deterministic plumbing (sync/cleanup/train/backup) — stays Celery",
        "sensor": "Polling/detection/scoring — stays Celery (feeds events, not cognition itself)",
        "unclassified": "Heuristic couldn't place it — needs a human look",
    }
    for cls in ("legacy_cognition", "anchor", "maintenance", "sensor", "unclassified"):
        lines.append(f"| {cls} | {len(by_class.get(cls, []))} | {meaning[cls]} |")
    lines.append("")
    plumbing_count = len(by_class.get("maintenance", [])) + len(by_class.get("sensor", [])) + len(by_class.get("anchor", []))
    lines.append(f"**Plumbing if migration completes as proposed:** maintenance + sensor + anchor "
                f"= {plumbing_count} (target from the plan: ≤30 — {'within budget' if plumbing_count <= 30 else f'{plumbing_count - 30} over budget, review candidates for retirement below'}).")
    lines.append(f"**Unclassified needing hand review before any count is final:** {len(by_class.get('unclassified', []))}.")
    lines.append("")

    for cls in ("legacy_cognition", "unclassified", "anchor", "maintenance", "sensor"):
        cls_jobs = by_class.get(cls, [])
        if not cls_jobs:
            continue
        lines.append(f"## {cls} ({len(cls_jobs)})")
        lines.append("")
        if cls == "legacy_cognition":
            lines.append("| key | task_name | schedule | enabled | last_status | last_run_at | last_error | proposed wake_reason |")
            lines.append("|---|---|---|---|---|---|---|---|")
        else:
            lines.append("| key | task_name | schedule | enabled | last_status | last_run_at | last_error |")
            lines.append("|---|---|---|---|---|---|---|")
        for j in cls_jobs:
            sched = j["cron_expr"] if j["schedule_kind"] == "cron" else f"every {j['interval_seconds']}s"
            err = (j["last_error"] or "")[:80].replace("|", "/").replace("\n", " ")
            last_run = j["last_run_at"].isoformat() if j["last_run_at"] else "never"
            row = f"| `{j['key']}` | `{j['task_name']}` | {sched} | {'✅' if j['enabled'] else '❌'} | {j['last_status'] or '?'} | {last_run} | {err} |"
            if cls == "legacy_cognition":
                row = row[:-1] + f" {_propose_wake_reason(j)} |"
            lines.append(row)
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=None)
    args = parser.parse_args()
    report = build_report()
    if args.out:
        Path(args.out).write_text(report)
        print(f"Wrote {len(report)} bytes to {args.out}")
    else:
        print(report)


if __name__ == "__main__":
    main()
