#!/usr/bin/env python3
"""
Arc 5 dry-run manifest — notes matching machine-generated criteria
(SARA_ALIVE_BUILD_PLAN Arc 5.3, per David's 2026-07-29 design-first guidance).

Produces a document listing every note whose TITLE matches a known
machine-generated pattern (agent dispatch results, background research
write-ups) — candidates for migration out of the garden (David's notes,
zero machine-generated content) into the record (episodes, agent results,
run logs — queryable, never rendered as notes).

Deliberately conservative: only clear, high-confidence title prefixes.
Folder membership (`📁 Agent Workspace`) was checked and REJECTED as a
classification signal — sampling it live showed genuine David-authored
reference notes mixed in with agent results, so folder alone would
misclassify. Title prefix is the only signal used here.

Read-only. Produces a manifest for review — does NOT move, copy, or delete
any note. Per the plan: migration (once approved) copies matched notes to
the record store preserving original IDs; garden rows are removed only
after the copies verify.

Run:
  docker compose -f docker-compose.dev.yml exec -T backend \\
    python scripts/arc5_notes_manifest.py [--out /path/to/manifest.md]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

DEFAULT_USER_ID = "64f37c56-85cb-4590-8de9-adfc17d343ed"

# (label, SQL LIKE pattern) — every pattern here was individually verified
# live against a title sample before inclusion (see commit message).
PATTERNS = [
    ("Agent Result:%", "Agent dispatch tool result notes (research/executor + agent_dispatch write-back)"),
    ("✅ Agent Report:%", "Agent dispatch report notes, alternate prefix"),
    ("Background Research:%", "Background/deep-research write-ups"),
]


def build_manifest(user_id: str) -> str:
    from sqlalchemy import text
    from app.db.session import SessionLocal

    db = SessionLocal()
    try:
        total_notes = db.execute(text(
            "SELECT COUNT(*) FROM note WHERE user_id = :uid"
        ), {"uid": user_id}).scalar() or 0

        lines = []
        lines.append("# Arc 5 dry-run manifest — machine-generated notes (garden -> record)")
        lines.append("")
        lines.append(f"Generated by `scripts/arc5_notes_manifest.py`. David's total notes: {total_notes}. "
                     f"Read-only — nothing has been moved, copied, or deleted.")
        lines.append("")

        grand_total = 0
        all_rows = []
        lines.append("## Census")
        lines.append("")
        lines.append("| Pattern | Meaning | Count |")
        lines.append("|---|---|---|")
        pattern_counts = {}
        for pattern, meaning in PATTERNS:
            count = db.execute(text(
                "SELECT COUNT(*) FROM note WHERE user_id = :uid AND title LIKE :pat"
            ), {"uid": user_id, "pat": pattern}).scalar() or 0
            pattern_counts[pattern] = count
            grand_total += count
            lines.append(f"| `{pattern}` | {meaning} | {count} |")
        lines.append(f"| **Total candidates** | | **{grand_total}** |")
        lines.append(f"| Remaining garden notes (unaffected) | | {total_notes - grand_total} |")
        lines.append("")
        lines.append("**Rejected signal:** folder `📁 Agent Workspace` (72 notes) was checked and is NOT "
                     "used for classification — sampling it live found genuine David-authored reference "
                     "notes (e.g. saved Gmail search-operator notes) mixed in with agent results. Title "
                     "prefix only.")
        lines.append("")

        for pattern, meaning in PATTERNS:
            rows = db.execute(text("""
                SELECT id, title, created_at FROM note
                WHERE user_id = :uid AND title LIKE :pat
                ORDER BY created_at DESC
            """), {"uid": user_id, "pat": pattern}).fetchall()
            if not rows:
                continue
            lines.append(f"## `{pattern}` ({len(rows)})")
            lines.append("")
            lines.append("Most recent 10 (full list has all IDs; truncated here for readability):")
            lines.append("")
            lines.append("| id | title | created_at |")
            lines.append("|---|---|---|")
            for r in rows[:10]:
                title = (r.title or "")[:90].replace("|", "/").replace("\n", " ")
                lines.append(f"| `{r.id}` | {title} | {r.created_at} |")
            lines.append("")
            if len(rows) > 10:
                lines.append(f"...and {len(rows) - 10} more.")
                lines.append("")
            all_rows.extend([(r.id, pattern) for r in rows])

        lines.append("## Full ID list (for the migration script, once approved)")
        lines.append("")
        lines.append("```")
        for note_id, pattern in all_rows:
            lines.append(note_id)
        lines.append("```")

        return "\n".join(lines)
    finally:
        db.close()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=None)
    parser.add_argument("--user-id", default=DEFAULT_USER_ID)
    args = parser.parse_args()
    manifest = build_manifest(args.user_id)
    if args.out:
        Path(args.out).write_text(manifest)
        print(f"Wrote {len(manifest)} bytes to {args.out}")
    else:
        print(manifest)


if __name__ == "__main__":
    main()
