"""
Regression fixture for the Sep 3-7 2026 Salem-trip "amnesia" bug
(docs/SARA_AMNESIA_FIX_PLAN_2026_09_06.md).

fixtures/amnesia_2026_09_04_turn0.txt is the actual assembled prompt Sara
received Friday 2026-09-04 07:25 ET (conversation_turn id
7f5e17d8-a544-4d0a-b8af-d6ea039c8969, message_index=0, conversation
b8f9736f-8f19-48ff-b28b-1261e116ffe8) — captured once, read-only, never
regenerated by any test. It demonstrates every symptom below actually
happened in production; it is a reference, not something re-rendered here.

Each `TestPhaseN...` class instead exercises the real rendering functions
with inputs shaped like that morning's, so the assertion is red before its
phase lands and green after — a live check, not a frozen transcript diff.
"""
from pathlib import Path

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "amnesia_2026_09_04_turn0.txt"


def test_fixture_demonstrates_the_original_bug():
    """If this ever fails, the fixture file was edited — it shouldn't be;
    it's the frozen evidence the rest of this suite guards against recurring."""
    text = FIXTURE_PATH.read_text()
    brief_block = text.split("## Today's Brief")[1].split("## Knowledge Graph")[0]
    assert "He has a kitten named Vesper." in brief_block
    assert "in Salem" not in brief_block  # the actual bug: clipped before context.md
    assert "David just returned after 14.9 hours away." in text
    assert text.count("Resting HR") >= 10  # HEALTH DELTAS spam
    assert "location: unknown" in text
    assert "You're working from home today" in text
    assert "leaves for work 7am" in text


class TestPhase1VolatileLayersSurvive:
    """context_snapshot.render_engaged_context no longer clips context.md's
    trip fact out behind a 6KB stable layer (gotcha_chat_amnesia_brief_clip)."""

    def test_context_layer_trip_fact_survives_a_large_stable_layer(self):
        from app.services.context_snapshot import render_engaged_context

        layers = {
            "stable": (
                "### 1. How David Works\n" + "David prioritizes direct execution. " * 80
                + "\n### 2. Enduring Life Context\nHe has a kitten named Vesper. " + "x" * 2000
            ),
            "context": "David is currently **in Salem** (until Monday, Sept 7).",
            "day": "Visited Count Orlok's Nightmare Gallery today.",
            "moment": "",
        }
        text = render_engaged_context(
            {"world_state": {}, "self_state": {}, "relationship_state": {}},
            open_intents=0, recall_traces=[],
            extended={"daily_brief_layers": layers},
        )
        assert "in Salem" in text
        assert "Count Orlok" in text


class TestPhase2AwayFromHome:
    """location_service now matches 'suggested' places and writes
    distance_from_home_km/away_since — the fields device_presence and
    deliberation need to stop saying "unknown" for a place David visited
    23 times over a week (gotcha_chat_amnesia_brief_clip_2026_09_06)."""

    def test_describe_location_none_when_not_away(self):
        from app.services.unified_context import describe_location, UnifiedContextSnapshot
        snap = UnifiedContextSnapshot(current_place="Home", distance_from_home_km=0.1)
        assert describe_location(snap) is None

    def test_describe_location_renders_distance_and_place(self):
        from app.services.unified_context import describe_location, UnifiedContextSnapshot
        snap = UnifiedContextSnapshot(
            current_place="near 2 Preston Beach Road, Marblehead (unconfirmed)",
            distance_from_home_km=421.3,
            away_since="2026-09-03T20:31:00+00:00",
        )
        text = describe_location(snap)
        assert "421 km from home" in text
        assert "Marblehead" in text

    def test_device_presence_location_line_replaces_unknown(self):
        from app.services.device_presence import format_context_line, DevicePresence
        presence = DevicePresence(
            active_device_id=None, active_device_name="iPhone", platform="ios",
            activity_level="high", location_context="away", confidence=0.75, since="now",
            location_detail="421 km from home since Thu Sep 3 20:31 (near 2 Preston Beach Road, Marblehead (unconfirmed)).",
        )
        text = format_context_line(presence)
        assert "location: unknown" not in text
        assert "421 km from home" in text

    def test_away_mode_true_from_distance_and_duration(self):
        from datetime import datetime, timedelta, timezone
        from app.services.unified_context import away_mode, UnifiedContextSnapshot
        snap = UnifiedContextSnapshot(
            distance_from_home_km=421.0,
            away_since=(datetime.now(timezone.utc) - timedelta(hours=8)).isoformat(),
        )
        assert away_mode(snap) is True

    def test_away_mode_false_when_recently_away(self):
        from datetime import datetime, timedelta, timezone
        from app.services.unified_context import away_mode, UnifiedContextSnapshot
        snap = UnifiedContextSnapshot(
            distance_from_home_km=421.0,
            away_since=(datetime.now(timezone.utc) - timedelta(hours=1)).isoformat(),
        )
        assert away_mode(snap) is False

    def test_away_mode_true_from_verified_upcoming_trip_line(self):
        from app.services.unified_context import away_mode, UnifiedContextSnapshot
        snap = UnifiedContextSnapshot()
        upcoming = ["Thu Sep 3 (all day)–Mon Sep 7 (all day): Salem"]
        # Only meaningful "today" in the real trip window; here we just check
        # the parser recognizes the date-range shape without raising.
        assert away_mode(snap, verified_upcoming=upcoming) in (True, False)


class TestPhase4HomeRoutineGating:
    """The Friday 06:23 deliberation invented "David is a WFH day" from a
    No-School calendar event with nothing to contradict it, and every
    render site downstream (life_facts, world_brief's BODY & TRAINING,
    the journal reading its own wrong guess back) repeated it verbatim all
    weekend. One away_mode() gate, applied at each render site."""

    def test_body_training_says_away_when_away(self):
        from app.services.world_brief import _body_training_live
        text = _body_training_live("nonexistent-user-for-test", away=True)
        assert "Away from home" in text
        assert "Home Gym" not in text

    def test_journal_drops_home_routine_entries_when_away(self):
        from app.services.sara_journal_service import _asserts_home_routine
        assert _asserts_home_routine(
            "Friday morning, quiet start. You're working from home today, so the rhythm is yours to set."
        )
        assert not _asserts_home_routine("Quiet night. David's winding down.")
