"""Versioned, idempotent workout command service.

SARA_APPLE_WATCH_FITNESS_IMPLEMENTATION_PLAN_2026_07_25 §5, §6.2, §6.5-§6.8.

Why this exists: `workout_session_service` was written when the phone was the
only controller, so each mutation was "read state, write state, commit". With
the Watch as a second controller that stops being safe — a retried Log Set over
a flaky link writes a second set, and two devices can interleave writes on the
same row.

Every mutation now goes through `execute()`, which is the ONLY place workout
state changes. It follows the sequence in §6.2 exactly:

    begin -> replay if command_id seen -> lock the session row -> validate
    user/session/status/version -> apply once -> bump version -> store the
    result projection -> commit

`command_id` is generated by the client *before* sending, so a command whose
response was lost can be retried byte-identically and will replay the original
result instead of applying twice.

Coaching is deliberately NOT part of this path (§6.7). A set is durable and
acknowledged the moment it commits; the LLM sentence arrives later as a
`workout_session_event` row. A dead LLM can no longer make `Log Set` feel
broken.

The legacy `/workout-session/*` endpoints call in here too, via the adapters in
`workout_session_service`, so there is exactly one mutation implementation
(§6.5) rather than a phone path and a Watch path that drift apart.
"""

from __future__ import annotations

import asyncio
import json
import logging
import uuid
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Dict, List, Optional

from sqlalchemy import text
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

SCHEMA_VERSION = 1

# How long an in-session proposal stays actionable before it is stale advice.
PROPOSAL_TTL_SECONDS = 300
# Coaching older than this is dropped rather than spoken (§6.7).
COACHING_TTL_SECONDS = 90

MUTATING_KINDS = {
    "log_set",
    "select_exercise",
    "set_variant",
    "skip_exercise",
    "rest_start",
    "rest_stop",
    "complete",
    "abandon",
    "approve_proposal",
    "reject_proposal",
    "healthkit_state",
    "set_policy",
}

# UI effort language -> numeric RPE. "easy/right/hard" is what the Watch and the
# phone panel show; light/moderate/failed are the older chat-side words.
EFFORT_RPE = {
    "easy": 6, "light": 6,
    "right": 7, "moderate": 7,
    "hard": 9,
    "failed": 10,
}

# Bounded policies Sara may operate inside without re-asking (§6.9). These are
# the defaults for a user who has never approved anything: rest automation on
# (it is what the phone already does today), speech off until David enables it.
DEFAULT_POLICY: Dict[str, Any] = {
    "adaptive_rest_enabled": True,
    "rest_range_seconds": [45, 210],
    "auto_start_rest_after_set": True,
    "speak_routine_coaching": False,
    "speak_prs": False,
    "speak_proposals": False,
}


class WorkoutConflict(Exception):
    """A command could not be applied against the current state.

    `code` is the machine-readable reason the client branches on:
      active_workout_conflict / version_conflict / session_mismatch /
      no_active_session / proposal_stale
    """

    def __init__(self, code: str, message: str, projection: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.projection = projection


class WorkoutCommandService:
    # ────────────────────────────────────────────────────────────────────
    # Session loading / projection
    # ────────────────────────────────────────────────────────────────────

    def _lock_active_row(self, db: Session, user_id: str) -> Optional[Dict[str, Any]]:
        """Fetch the user's active session with a row lock held for the txn.

        FOR UPDATE is what serialises two devices racing the same mutation:
        the second one blocks until the first has bumped `version`, and then
        fails its expected_version check instead of overwriting.
        """
        row = db.execute(text("""
            SELECT id, user_id, template_id, status, started_at, completed_at,
                   current_exercise_index, current_set_index, workout_snapshot,
                   rest_timer_started_at, rest_timer_duration_seconds,
                   total_sets_completed, total_volume, notes, updated_at,
                   version, origin_device, start_attempt_id,
                   healthkit_state, healthkit_workout_uuid, healthkit_activity_type,
                   healthkit_started_at, healthkit_ended_at, last_device_sync_at
            FROM active_workout_session
            WHERE user_id = :uid AND status = 'active'
            FOR UPDATE
        """), {"uid": user_id}).fetchone()
        return self._hydrate(row) if row else None

    def _load_by_id(self, db: Session, session_id: str) -> Optional[Dict[str, Any]]:
        row = db.execute(text("""
            SELECT id, user_id, template_id, status, started_at, completed_at,
                   current_exercise_index, current_set_index, workout_snapshot,
                   rest_timer_started_at, rest_timer_duration_seconds,
                   total_sets_completed, total_volume, notes, updated_at,
                   version, origin_device, start_attempt_id,
                   healthkit_state, healthkit_workout_uuid, healthkit_activity_type,
                   healthkit_started_at, healthkit_ended_at, last_device_sync_at
            FROM active_workout_session WHERE id = :sid
        """), {"sid": session_id}).fetchone()
        return self._hydrate(row) if row else None

    @staticmethod
    def _hydrate(row) -> Dict[str, Any]:
        s = dict(row._mapping)
        snap = s.get("workout_snapshot")
        if isinstance(snap, str):
            s["workout_snapshot"] = json.loads(snap) if snap else {}
        elif snap is None:
            s["workout_snapshot"] = {}
        s["total_volume"] = float(s["total_volume"]) if s.get("total_volume") else 0.0
        s["version"] = int(s.get("version") or 1)
        return s

    def _name_counts(self, db: Session, session_id: str) -> Dict[str, int]:
        rows = db.execute(text("""
            SELECT exercise_id, COUNT(*) AS c FROM workout_log
            WHERE active_session_id = :sid GROUP BY exercise_id
        """), {"sid": session_id}).fetchall()
        return {r.exercise_id: int(r.c) for r in rows}

    def projection(
        self, db: Session, session: Optional[Dict[str, Any]], *, compact: bool = False
    ) -> Optional[Dict[str, Any]]:
        """The complete renderable state both devices agree on (§5.1).

        Everything a controller needs to draw a screen is in here, so a device
        that has been offline can catch up from one payload instead of
        replaying a change log.
        """
        if not session:
            return None

        from app.services.workout_session_service import workout_session_service as legacy

        snap = session.get("workout_snapshot") or {}
        exercises: List[Dict[str, Any]] = snap.get("exercises") or []
        counts = self._name_counts(db, session["id"])

        for ex in exercises:
            target = ex.get("sets", 0) or 0
            ex["completed_sets"] = min(counts.get(legacy._effective_name(ex), 0), target)
            # Older sessions predate the approved/calculated split — treat the
            # value they were started with as already approved.
            ex.setdefault("approved_weight", ex.get("suggested_weight"))
            ex.setdefault("calculated_suggestion", ex.get("suggested_weight"))

        cur_idx = session.get("current_exercise_index") or 0
        cur = exercises[cur_idx] if 0 <= cur_idx < len(exercises) else None

        rest_started = session.get("rest_timer_started_at")
        rest_duration = session.get("rest_timer_duration_seconds")
        rest_active = False
        if rest_started and rest_duration:
            elapsed = (datetime.now(timezone.utc) - rest_started).total_seconds()
            rest_active = elapsed < rest_duration

        proj: Dict[str, Any] = {
            "schema_version": SCHEMA_VERSION,
            "session_id": session["id"],
            "version": session["version"],
            "status": session["status"],
            "started_at": _iso(session.get("started_at")),
            "origin_device": session.get("origin_device"),
            "template": {
                "id": session.get("template_id"),
                "name": snap.get("template_name") or "Workout",
                "is_deload": bool(snap.get("is_deload")),
            },
            "cursor": {
                "exercise_index": cur_idx,
                "set_index": session.get("current_set_index") or 0,
            },
            "progress": {
                "completed_sets": session.get("total_sets_completed") or 0,
                "total_sets": snap.get("total_sets") or sum((e.get("sets") or 0) for e in exercises),
                "total_volume": session.get("total_volume") or 0.0,
            },
            "current_exercise": _exercise_view(cur) if cur else None,
            "rest": {
                "active": rest_active,
                "started_at": _iso(rest_started),
                "duration_seconds": rest_duration,
            },
            "healthkit": {
                "state": session.get("healthkit_state"),
                "workout_uuid": session.get("healthkit_workout_uuid"),
                "activity_type": session.get("healthkit_activity_type"),
                "started_at": _iso(session.get("healthkit_started_at")),
                "ended_at": _iso(session.get("healthkit_ended_at")),
            },
            "pending_proposal": self._pending_proposal(db, session["user_id"], session["id"]),
            "updated_at": _iso(session.get("updated_at")),
        }
        if not compact:
            # The Watch renders from `current_exercise` alone; the phone needs
            # the whole list for the exercise picker and jump-in-any-order.
            proj["exercises"] = [_exercise_view(e) for e in exercises]
        return proj

    # ────────────────────────────────────────────────────────────────────
    # Start (§4.2, §4.3, §6.6)
    # ────────────────────────────────────────────────────────────────────

    async def start(
        self,
        db: Session,
        user_id: str,
        template_id: str,
        *,
        start_attempt_id: Optional[str] = None,
        origin_device: str = "phone",
        on_conflict: str = "error",
        healthkit_started_at: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Create (or replay, or refuse to clobber) the canonical session.

        `on_conflict="error"` is the §6.6 contract: an active workout for a
        different template is a 409 the user resolves, never a silent abandon.
        The legacy phone endpoint passes "abandon" while
        WORKOUT_COMMAND_V2_ENABLED is off so today's behaviour is unchanged
        until the phone has moved over.
        """
        try:
            # 1. Idempotent replay: the same start attempt returns the same
            #    session, so a Watch retrying through a dropped link cannot
            #    create a second workout.
            if start_attempt_id:
                existing = db.execute(text("""
                    SELECT id FROM active_workout_session
                    WHERE user_id = :uid AND start_attempt_id = :aid
                    ORDER BY started_at DESC LIMIT 1
                """), {"uid": user_id, "aid": start_attempt_id}).fetchone()
                if existing:
                    sess = self._load_by_id(db, existing.id)
                    return {"status": "replayed", "projection": self.projection(db, sess)}

            active = self._lock_active_row(db, user_id)
            if active:
                same_template = str(active.get("template_id") or "") == str(template_id)
                if same_template:
                    # Resume, don't restart — the sets already logged stand.
                    return {"status": "resumed", "projection": self.projection(db, active)}
                if on_conflict == "abandon":
                    await self._apply_abandon(db, active, delete_sets=True)
                else:
                    raise WorkoutConflict(
                        "active_workout_conflict",
                        "A different workout is already active. Resume it or end it first.",
                        self.projection(db, active),
                    )

            projection = await self._create_session(
                db, user_id, template_id,
                start_attempt_id=start_attempt_id,
                origin_device=origin_device,
                healthkit_started_at=healthkit_started_at,
            )
            db.commit()
            return {"status": "accepted", "projection": projection}

        except WorkoutConflict:
            db.rollback()
            raise
        except Exception:
            db.rollback()
            logger.exception("[WorkoutCommand] start failed")
            raise

    async def _create_session(
        self,
        db: Session,
        user_id: str,
        template_id: str,
        *,
        start_attempt_id: Optional[str],
        origin_device: str,
        healthkit_started_at: Optional[str],
    ) -> Dict[str, Any]:
        from app.services.progressive_overload import get_deload_state
        from app.services.workout_session_service import workout_session_service as legacy

        row = db.execute(text("""
            SELECT id, name, phase_id, scheduled_days, exercises, notes
            FROM fitness_template WHERE id = :tid AND user_id = :uid
        """), {"tid": template_id, "uid": user_id}).fetchone()
        if not row:
            raise ValueError(f"Template {template_id} not found")

        template = dict(row._mapping)
        raw = template.get("exercises") or "[]"
        specs = json.loads(raw) if isinstance(raw, str) else (raw or [])

        deload = get_deload_state(db=db, user_id=user_id, on_date=date.today())
        is_deload = deload["is_deload"]
        enforce_approval = _v2_enabled()
        consumed_approvals = self._approved_next_session_weights(db, user_id) if enforce_approval else {}

        snapshots = []
        for spec in specs:
            name = spec.get("name")
            target_sets = spec.get("sets", 3)
            target_reps = spec.get("reps", "8-10")
            suggestion = legacy._compute_suggestion(user_id, name, target_reps, is_deload, db)
            calculated = suggestion["suggested_weight"]

            # §6.8 — calculation is not application. The workout starts on the
            # weight David last actually approved; Sara's new number rides along
            # as a proposal she has to be told to apply. With the v2 flag off
            # this collapses to today's behaviour.
            approved = calculated
            if enforce_approval:
                # A progression he already approved out of the gym IS the
                # current prescription — otherwise approving it did nothing and
                # he'd be asked the same question again at the rack.
                approved = (
                    consumed_approvals.get(name)
                    or _last_approved_weight(suggestion.get("last_session"))
                    or calculated
                )

            effective_sets = target_sets
            if is_deload:
                try:
                    effective_sets = max(2, int(target_sets) // 2)
                except (TypeError, ValueError):
                    effective_sets = target_sets

            snapshots.append({
                "name": name,
                "variant": None,
                "sets": effective_sets,
                "sets_original": target_sets if is_deload else None,
                "reps": target_reps,
                "rpe_target": spec.get("rpe_target", 7),
                "rest_seconds": spec.get("rest_seconds", 120),
                "notes": spec.get("notes"),
                "metric_type": spec.get("metric_type", "reps"),
                "is_per_side": bool(spec.get("is_per_side", False)),
                "superset_group": spec.get("superset_group"),
                "set_technique": spec.get("set_technique"),
                # `suggested_weight` stays the field the existing phone UI
                # reads, and always holds the value to actually lift.
                "suggested_weight": approved,
                "approved_weight": approved,
                "calculated_suggestion": calculated,
                "progression_note": suggestion["progression_note"],
                "last_session": suggestion["last_session"],
            })

        snapshot = {
            "template_id": template_id,
            "template_name": template["name"],
            "template_notes": template.get("notes"),
            "exercises": snapshots,
            "total_sets": sum(e["sets"] for e in snapshots),
            "is_deload": is_deload,
            "week_of_phase": deload.get("week_of_phase"),
            "deload_week": deload.get("deload_week"),
            "phase_name": deload.get("phase_name"),
        }

        session_id = str(uuid.uuid4())
        db.execute(text("""
            INSERT INTO workout (id, user_id, title, status)
            VALUES (:id, :uid, :title, 'in_progress')
        """), {"id": session_id, "uid": user_id, "title": template["name"]})

        db.execute(text("""
            INSERT INTO active_workout_session (
                id, user_id, template_id, status, workout_snapshot,
                version, origin_device, start_attempt_id,
                healthkit_state, healthkit_started_at, last_device_sync_at
            ) VALUES (
                :id, :uid, :tid, 'active', CAST(:snap AS jsonb),
                1, :origin, :aid,
                :hk_state, :hk_started, NOW()
            )
        """), {
            "id": session_id, "uid": user_id, "tid": template_id,
            "snap": json.dumps(snapshot), "origin": origin_device,
            "aid": start_attempt_id,
            "hk_state": "running" if healthkit_started_at else None,
            "hk_started": healthkit_started_at,
        })

        session = self._load_by_id(db, session_id)

        # A carried-over approval applies to exactly this workout. Retiring it
        # here stops it silently re-applying to every future session, which
        # would turn one "yes" into standing permission.
        if consumed_approvals:
            db.execute(text("""
                UPDATE workout_adjustment_proposal
                SET status = 'superseded', resolved_at = NOW()
                WHERE user_id = :uid AND kind = 'next_session_weight' AND status = 'approved'
            """), {"uid": user_id})

        # Surface the held-back progression as an approvable proposal rather
        # than quietly lifting more than David agreed to.
        if enforce_approval:
            for idx, ex in enumerate(snapshots):
                calc, appr = ex.get("calculated_suggestion"), ex.get("approved_weight")
                if calc is not None and appr is not None and float(calc) != float(appr):
                    self._create_proposal(
                        db, user_id, session_id,
                        kind="exercise_weight",
                        scope={"exercise_index": idx},
                        current_value={"weight": appr},
                        proposed_value={"weight": calc},
                        reason=ex.get("progression_note") or "Progression from your last session.",
                        evidence={"last_session": ex.get("last_session")},
                        ttl_seconds=None,
                    )

        return self.projection(db, session)

    # ────────────────────────────────────────────────────────────────────
    # Command execution (§5.2, §6.2)
    # ────────────────────────────────────────────────────────────────────

    async def execute(self, db: Session, user_id: str, envelope: Dict[str, Any]) -> Dict[str, Any]:
        """Apply one command envelope exactly once."""
        command_id = envelope.get("command_id")
        kind = envelope.get("kind")
        if not command_id:
            raise ValueError("command_id is required")
        if kind not in MUTATING_KINDS:
            raise ValueError(f"unknown command kind: {kind!r}")

        payload = envelope.get("payload") or {}
        expected_version = envelope.get("expected_version")
        claimed_session = envelope.get("session_id")
        origin = envelope.get("origin_device") or "phone"

        try:
            # 2. Replay — return the stored result verbatim. Both devices then
            #    converge on the same answer no matter who retried.
            prior = db.execute(text("""
                SELECT result FROM workout_session_command
                WHERE command_id = :cid AND user_id = :uid
            """), {"cid": command_id, "uid": user_id}).fetchone()
            if prior:
                stored = prior.result or {}
                if isinstance(stored, str):
                    stored = json.loads(stored)
                return {**stored, "status": "replayed"}

            # 3. Lock.
            session = self._lock_active_row(db, user_id)

            # Two kinds are about consent rather than session state and must
            # work with no workout running: standing policy, and resolving a
            # proposal. Post-workout progression is deliberately approved out
            # of the gym (§6.8) — requiring an active session would make those
            # proposals unanswerable until David was back under a bar.
            if kind == "set_policy":
                result = self._apply_set_policy(db, user_id, payload, origin)
                self._record_command(db, command_id, None, user_id, origin, kind,
                                     expected_version, payload, result, "applied")
                db.commit()
                return result

            if not session and kind in ("approve_proposal", "reject_proposal"):
                result = self._apply_resolve_proposal(
                    db, None, user_id, payload, origin, command_id,
                    approve=(kind == "approve_proposal"),
                )
                result = {"status": "accepted", "command_id": command_id,
                          "projection": None, **result}
                self._record_command(db, command_id, None, user_id, origin, kind,
                                     expected_version, payload, result, "applied")
                db.commit()
                return result

            if not session:
                raise WorkoutConflict("no_active_session", "No active workout session.")

            # 4. Validate. A command minted against a workout that has since
            #    ended must not land on its replacement.
            if claimed_session and str(claimed_session) != str(session["id"]):
                raise WorkoutConflict(
                    "session_mismatch",
                    "That action was for a different workout.",
                    self.projection(db, session),
                )
            if expected_version is not None and int(expected_version) != session["version"]:
                raise WorkoutConflict(
                    "version_conflict",
                    "The workout changed on another device.",
                    self.projection(db, session),
                )

            # 5. Apply once.
            extra = await self._dispatch(db, session, kind, payload, origin, command_id)

            # 6. Bump version (skipped for the terminal kinds, which set their
            #    own status and are already reloaded by the handler).
            if kind not in ("complete", "abandon"):
                self._bump(db, session["id"], origin)

            fresh = self._load_by_id(db, session["id"])
            result = {
                "status": "accepted",
                "command_id": command_id,
                "projection": self.projection(db, fresh),
                **extra,
            }

            # 7. Store the result so a replay is free and exact.
            self._record_command(db, command_id, session["id"], user_id, origin, kind,
                                 expected_version, payload, result, "applied")
            db.commit()

            # Coaching happens strictly after the commit (§6.7): the set is
            # already durable, so a hung LLM cannot make Log Set look broken.
            if kind == "log_set":
                self._schedule_coaching(user_id, session["id"], extra)
            return result

        except WorkoutConflict as c:
            db.rollback()
            try:
                self._record_command(db, command_id, claimed_session, user_id, origin, kind,
                                     expected_version, payload,
                                     {"status": "conflict", "code": c.code, "message": c.message},
                                     "conflict")
                db.commit()
            except Exception:
                db.rollback()
            raise
        except Exception:
            db.rollback()
            logger.exception(f"[WorkoutCommand] {kind} failed")
            raise

    async def _dispatch(
        self, db: Session, session: Dict[str, Any], kind: str,
        payload: Dict[str, Any], origin: str, command_id: str,
    ) -> Dict[str, Any]:
        if kind == "log_set":
            return await self._apply_log_set(db, session, payload, command_id)
        if kind == "select_exercise":
            return self._apply_select_exercise(db, session, payload)
        if kind == "set_variant":
            return self._apply_set_variant(db, session, payload)
        if kind == "skip_exercise":
            return self._apply_skip(db, session)
        if kind == "rest_start":
            return self._apply_rest_start(db, session, payload)
        if kind == "rest_stop":
            return self._apply_rest_stop(db, session)
        if kind == "complete":
            return await self._apply_complete(db, session, payload)
        if kind == "abandon":
            return await self._apply_abandon(db, session, delete_sets=True)
        if kind == "approve_proposal":
            return self._apply_resolve_proposal(
                db, session, session["user_id"], payload, origin, command_id, approve=True
            )
        if kind == "reject_proposal":
            return self._apply_resolve_proposal(
                db, session, session["user_id"], payload, origin, command_id, approve=False
            )
        if kind == "healthkit_state":
            return self._apply_healthkit_state(db, session, payload)
        raise ValueError(f"unhandled kind {kind}")

    def _bump(self, db: Session, session_id: str, origin: str) -> None:
        db.execute(text("""
            UPDATE active_workout_session
            SET version = version + 1, updated_at = NOW(),
                last_device_sync_at = NOW(), origin_device = COALESCE(origin_device, :origin)
            WHERE id = :sid
        """), {"sid": session_id, "origin": origin})

    def _record_command(
        self, db: Session, command_id: str, session_id: Optional[str], user_id: str,
        origin: str, kind: str, expected_version: Optional[int],
        payload: Dict[str, Any], result: Dict[str, Any], status: str,
    ) -> None:
        db.execute(text("""
            INSERT INTO workout_session_command (
                command_id, session_id, user_id, origin_device, kind,
                expected_version, payload, result, status, applied_at
            ) VALUES (
                :cid, :sid, :uid, :origin, :kind,
                :ver, CAST(:payload AS jsonb), CAST(:result AS jsonb), :status, NOW()
            )
            ON CONFLICT (command_id) DO NOTHING
        """), {
            "cid": command_id, "sid": session_id, "uid": user_id, "origin": origin,
            "kind": kind, "ver": expected_version,
            "payload": json.dumps(payload, default=str),
            "result": json.dumps(result, default=str),
            "status": status,
        })

    # ────────────────────────────────────────────────────────────────────
    # Mutations — none of these commit; `execute` owns the transaction.
    # ────────────────────────────────────────────────────────────────────

    async def _apply_log_set(
        self, db: Session, session: Dict[str, Any], payload: Dict[str, Any], command_id: str
    ) -> Dict[str, Any]:
        from app.services.workout_session_service import workout_session_service as legacy

        snap = session["workout_snapshot"]
        exercises: List[Dict[str, Any]] = snap.get("exercises") or []
        # The Watch names the exercise it thinks it is on; trusting that over
        # the shared cursor is what stops a phone-side jump mid-set from
        # silently redirecting the Watch's set to another lift.
        ex_idx = payload.get("exercise_index")
        ex_idx = session["current_exercise_index"] if ex_idx is None else int(ex_idx)
        if ex_idx < 0 or ex_idx >= len(exercises):
            raise WorkoutConflict("session_mismatch", "That exercise is no longer in this workout.")

        ex = exercises[ex_idx]
        base_name = ex["name"]
        exercise_name = legacy._effective_name(ex)
        target_sets = ex.get("sets") or 0

        rpe = payload.get("rpe")
        effort = (payload.get("effort") or payload.get("rpe_feeling") or "").strip().lower()
        if rpe is None and effort:
            rpe = EFFORT_RPE.get(effort, 7)

        weight = payload.get("weight")
        if weight is None:
            weight = ex.get("approved_weight") or ex.get("suggested_weight") or 0
        reps = payload.get("reps")
        if reps is None:
            target_reps = str(ex.get("reps", "8"))
            reps = int(target_reps.split("-")[0]) + 1 if "-" in target_reps else int(target_reps)

        counts_before = self._name_counts(db, session["id"])
        set_index = min(counts_before.get(exercise_name, 0), max(target_sets - 1, 0))

        log_id = str(uuid.uuid4())
        variant = (ex.get("variant") or "").strip() or None
        flags = json.dumps({"base_exercise": base_name, "variant": variant}) if variant else None
        db.execute(text("""
            INSERT INTO workout_log (
                id, workout_id, user_id, exercise_id, set_index, weight, reps, rpe, notes,
                session_date, session_time, active_session_id, flags, command_id
            ) VALUES (
                :id, :wid, :uid, :ex, :si, :w, :r, :rpe, :notes,
                :sdate, :stime, :sid, CAST(:flags AS json), :cid
            )
        """), {
            "id": log_id, "wid": session["id"], "uid": session["user_id"],
            "ex": exercise_name, "si": set_index + 1,
            "w": weight, "r": reps, "rpe": rpe, "notes": payload.get("notes"),
            "sdate": date.today(),
            # Real UTC instant — the container runs in ET, so a naive now()
            # would land 4-5h early and break the Watch time-overlap meld.
            "stime": datetime.now(timezone.utc),
            "sid": session["id"], "flags": flags, "cid": command_id,
        })

        # Cursor is derived from what is actually logged, never from an
        # incrementing pointer — that is what supports doing exercises in any
        # order and returning to a skipped machine.
        counts = self._name_counts(db, session["id"])
        done = legacy._completed_for(exercises, counts, ex_idx)
        exercise_complete = done >= (target_sets or 0)

        new_ex_idx, new_set_idx = ex_idx, done
        workout_complete, next_idx = False, None
        if exercise_complete:
            next_idx = legacy._next_incomplete_index(exercises, counts, ex_idx)
            if next_idx is None:
                workout_complete = True
            else:
                new_ex_idx = next_idx
                new_set_idx = legacy._completed_for(exercises, counts, next_idx)

        volume = Decimal(str(weight)) * Decimal(str(reps))
        db.execute(text("""
            UPDATE active_workout_session
            SET current_exercise_index = :ei, current_set_index = :si,
                total_sets_completed = total_sets_completed + 1,
                total_volume = total_volume + :vol
            WHERE id = :sid
        """), {"ei": new_ex_idx, "si": new_set_idx, "vol": volume, "sid": session["id"]})

        # Deterministic, immediately-known facts (§6.7 step 2) — PR and rest
        # length need no LLM, so they ride back on the acknowledgement.
        pr_result = None
        try:
            if weight and reps and float(weight) > 0 and int(reps) > 0:
                from app.routes.fitness import check_and_record_pr
                pr_result = await check_and_record_pr(
                    db=db, user_id=session["user_id"], exercise_name=exercise_name,
                    weight=weight, reps=reps, achieved_at=date.today(), workout_set_id=log_id,
                )
                if pr_result and pr_result.get("is_pr"):
                    db.execute(text("UPDATE workout_log SET is_pr = true WHERE id = :id"), {"id": log_id})
        except Exception as e:
            logger.warning(f"[WorkoutCommand] PR check failed (non-fatal): {e}")

        policy = self.get_policy(db, session["user_id"])
        rest_seconds = 0
        if not workout_complete and policy.get("adaptive_rest_enabled", True):
            lo, hi = (policy.get("rest_range_seconds") or [45, 210])[:2]
            rest_seconds = max(int(lo), min(legacy._smart_rest_seconds(exercise_name, rpe), int(hi)))
            # Server-side auto-start is what lets the Watch show a rest
            # countdown it never asked for. The phone has always driven its own
            # timer locally, so this stays off until the v2 cutover to keep the
            # current phone behaviour bit-identical.
            if _v2_enabled() and policy.get("auto_start_rest_after_set", True):
                db.execute(text("""
                    UPDATE active_workout_session
                    SET rest_timer_started_at = NOW(), rest_timer_duration_seconds = :d
                    WHERE id = :sid
                """), {"d": rest_seconds, "sid": session["id"]})

        # An RPE that overshoots the approved target is a recommendation, not a
        # licence to change the next set (§11.2).
        proposal = None
        if not workout_complete and rpe is not None:
            proposal = self._maybe_propose_weight(
                db, session, exercises, new_ex_idx, rpe, reps, float(weight)
            )

        return {
            "logged": {
                "id": log_id, "exercise": exercise_name, "exercise_index": ex_idx,
                "set_number": set_index + 1, "weight": float(weight), "reps": int(reps), "rpe": rpe,
            },
            "pr": pr_result if (pr_result and pr_result.get("is_pr")) else None,
            "rest_seconds": rest_seconds,
            "exercise_complete": exercise_complete and not workout_complete,
            "workout_complete": workout_complete,
            "next_exercise_index": None if workout_complete else new_ex_idx,
            "proposal": proposal,
        }

    def _apply_select_exercise(self, db: Session, session: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
        from app.services.workout_session_service import workout_session_service as legacy
        exercises = (session["workout_snapshot"].get("exercises") or [])
        idx = int(payload.get("exercise_index", -1))
        if idx < 0 or idx >= len(exercises):
            raise ValueError(f"Exercise index {idx} out of range")
        counts = self._name_counts(db, session["id"])
        set_idx = legacy._completed_for(exercises, counts, idx)
        db.execute(text("""
            UPDATE active_workout_session
            SET current_exercise_index = :ei, current_set_index = :si WHERE id = :sid
        """), {"ei": idx, "si": set_idx, "sid": session["id"]})
        return {"exercise": exercises[idx]["name"], "current_set_index": set_idx}

    def _apply_set_variant(self, db: Session, session: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
        from app.services.workout_session_service import workout_session_service as legacy
        snap = session["workout_snapshot"]
        exercises = snap.get("exercises") or []
        idx = int(payload.get("exercise_index", -1))
        if idx < 0 or idx >= len(exercises):
            raise ValueError(f"Exercise index {idx} out of range")

        ex = exercises[idx]
        clean = (payload.get("variant") or "").strip()
        ex["variant"] = None if (not clean or clean.lower() == (ex.get("name") or "").lower()) else clean

        # Re-scope the prescription to the machine actually being used, so hack
        # squat weights never land on the barbell squat's history.
        effective = legacy._effective_name(ex)
        suggestion = legacy._compute_suggestion(
            session["user_id"], effective, ex.get("reps", "8-10"), bool(snap.get("is_deload")), db
        )
        calculated = suggestion["suggested_weight"]
        approved = calculated
        if _v2_enabled():
            approved = _last_approved_weight(suggestion.get("last_session")) or calculated
        ex["suggested_weight"] = approved
        ex["approved_weight"] = approved
        ex["calculated_suggestion"] = calculated
        ex["progression_note"] = suggestion["progression_note"]
        ex["last_session"] = suggestion["last_session"]

        db.execute(text("""
            UPDATE active_workout_session SET workout_snapshot = CAST(:snap AS jsonb) WHERE id = :sid
        """), {"snap": json.dumps(snap), "sid": session["id"]})

        if idx == session["current_exercise_index"]:
            counts = self._name_counts(db, session["id"])
            db.execute(text("""
                UPDATE active_workout_session SET current_set_index = :si WHERE id = :sid
            """), {"si": legacy._completed_for(exercises, counts, idx), "sid": session["id"]})

        return {
            "exercise_index": idx, "variant": ex["variant"], "effective_name": effective,
            "approved_weight": approved, "calculated_suggestion": calculated,
            "last_session": ex["last_session"],
        }

    def _apply_skip(self, db: Session, session: Dict[str, Any]) -> Dict[str, Any]:
        from app.services.workout_session_service import workout_session_service as legacy
        exercises = session["workout_snapshot"].get("exercises") or []
        cur = session["current_exercise_index"]
        if not exercises:
            return {"skipped_exercise": None, "next_exercise": None, "workout_complete": True}

        counts = self._name_counts(db, session["id"])
        # A skipped exercise stays incomplete on purpose — the machine may free
        # up later, and _next_incomplete_index wraps back around to it.
        nxt = legacy._next_incomplete_index(exercises, counts, cur)
        new_idx = cur if nxt is None else nxt
        db.execute(text("""
            UPDATE active_workout_session
            SET current_exercise_index = :ei, current_set_index = :si WHERE id = :sid
        """), {
            "ei": new_idx,
            "si": legacy._completed_for(exercises, counts, new_idx),
            "sid": session["id"],
        })
        return {
            "skipped_exercise": exercises[cur]["name"] if cur < len(exercises) else None,
            "next_exercise": exercises[nxt]["name"] if nxt is not None else None,
            "workout_complete": nxt is None,
        }

    def _apply_rest_start(self, db: Session, session: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
        policy = self.get_policy(db, session["user_id"])
        lo, hi = (policy.get("rest_range_seconds") or [45, 210])[:2]
        duration = int(payload.get("duration_seconds") or payload.get("duration") or 120)
        duration = max(int(lo), min(duration, int(hi)))
        db.execute(text("""
            UPDATE active_workout_session
            SET rest_timer_started_at = NOW(), rest_timer_duration_seconds = :d WHERE id = :sid
        """), {"d": duration, "sid": session["id"]})
        return {"duration_seconds": duration}

    def _apply_rest_stop(self, db: Session, session: Dict[str, Any]) -> Dict[str, Any]:
        db.execute(text("""
            UPDATE active_workout_session
            SET rest_timer_started_at = NULL, rest_timer_duration_seconds = NULL WHERE id = :sid
        """), {"sid": session["id"]})
        return {"rest_stopped": True}

    async def _apply_complete(
        self, db: Session, session: Dict[str, Any], payload: Dict[str, Any]
    ) -> Dict[str, Any]:
        from app.services.workout_session_service import workout_session_service as legacy

        now = datetime.now(timezone.utc)
        started = session.get("started_at")
        duration_minutes = int((now - started).total_seconds() / 60) if started else 0

        hk_uuid = payload.get("healthkit_workout_uuid")
        db.execute(text("""
            UPDATE active_workout_session
            SET status = 'completed', completed_at = NOW(), updated_at = NOW(),
                version = version + 1,
                healthkit_state = COALESCE(:hk_state, healthkit_state),
                healthkit_workout_uuid = COALESCE(:hk_uuid, healthkit_workout_uuid),
                healthkit_ended_at = COALESCE(:hk_ended, healthkit_ended_at)
            WHERE id = :sid
        """), {
            "sid": session["id"],
            "hk_state": "ended" if hk_uuid else None,
            "hk_uuid": hk_uuid,
            "hk_ended": payload.get("healthkit_ended_at"),
        })
        if hk_uuid:
            db.execute(text("""
                UPDATE external_workout SET sara_session_id = :sid
                WHERE user_id = :uid AND external_id = :hk
            """), {"sid": session["id"], "uid": session["user_id"], "hk": hk_uuid})

        # Post-workout progression is a proposal for *next* time, approved out
        # of the gym rather than at the next start (§6.8).
        self._create_next_session_proposals(db, session)

        heart_rate = self._linked_heart_rate(db, session, hk_uuid) or legacy._meld_external_workout(
            db, session["user_id"], started, now
        )

        return {
            "summary": {
                "workout_name": session["workout_snapshot"].get("template_name", "Workout"),
                "duration_minutes": duration_minutes,
                "total_sets": session["total_sets_completed"],
                "total_volume": session["total_volume"],
                "exercises_completed": session["current_exercise_index"],
                "heart_rate": heart_rate,
            },
            "completed_at": now.isoformat(),
        }

    async def _apply_abandon(
        self, db: Session, session: Dict[str, Any], *, delete_sets: bool
    ) -> Dict[str, Any]:
        if delete_sets:
            # An abandoned workout leaves no trace in history — this preserves
            # the existing product rule (§4.6).
            db.execute(text("DELETE FROM workout_log WHERE active_session_id = :sid"), {"sid": session["id"]})
            db.execute(text("DELETE FROM workout WHERE id = :sid"), {"sid": session["id"]})
        db.execute(text("""
            UPDATE active_workout_session
            SET status = 'abandoned', completed_at = NOW(), updated_at = NOW(), version = version + 1
            WHERE id = :sid
        """), {"sid": session["id"]})
        db.execute(text("""
            UPDATE workout_adjustment_proposal
            SET status = 'superseded', resolved_at = NOW()
            WHERE session_id = :sid AND status = 'pending'
        """), {"sid": session["id"]})
        return {"abandoned": True}

    def _apply_healthkit_state(self, db: Session, session: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
        state = (payload.get("state") or "").strip() or None
        db.execute(text("""
            UPDATE active_workout_session
            SET healthkit_state = COALESCE(:st, healthkit_state),
                healthkit_workout_uuid = COALESCE(:uuid, healthkit_workout_uuid),
                healthkit_activity_type = COALESCE(:act, healthkit_activity_type),
                healthkit_started_at = COALESCE(CAST(:started AS timestamptz), healthkit_started_at),
                healthkit_ended_at = COALESCE(CAST(:ended AS timestamptz), healthkit_ended_at),
                last_device_sync_at = NOW()
            WHERE id = :sid
        """), {
            "st": state,
            "uuid": payload.get("workout_uuid"),
            "act": payload.get("activity_type"),
            "started": payload.get("started_at"),
            "ended": payload.get("ended_at"),
            "sid": session["id"],
        })
        return {"healthkit_state": state}

    def _apply_set_policy(
        self, db: Session, user_id: str, payload: Dict[str, Any], origin: str
    ) -> Dict[str, Any]:
        """Record a standing bounded approval (§6.9).

        Only keys Sara already knows about are stored — she cannot widen her
        own scope by inventing a policy name.
        """
        current = self.get_policy(db, user_id)
        incoming = payload.get("policy") or payload
        merged = {**current, **{k: v for k, v in incoming.items() if k in DEFAULT_POLICY}}

        rng = merged.get("rest_range_seconds") or DEFAULT_POLICY["rest_range_seconds"]
        try:
            lo, hi = int(rng[0]), int(rng[1])
            merged["rest_range_seconds"] = [max(15, lo), max(max(15, lo), min(hi, 600))]
        except (TypeError, ValueError, IndexError):
            merged["rest_range_seconds"] = DEFAULT_POLICY["rest_range_seconds"]

        db.execute(text("""
            INSERT INTO workout_approved_policy (user_id, policy, approved_by_device, updated_at)
            VALUES (:uid, CAST(:p AS jsonb), :dev, NOW())
            ON CONFLICT (user_id) DO UPDATE
              SET policy = CAST(:p AS jsonb), approved_by_device = :dev,
                  approved_at = NOW(), updated_at = NOW()
        """), {"uid": user_id, "p": json.dumps(merged), "dev": origin})
        return {"status": "accepted", "policy": merged}

    def get_policy(self, db: Session, user_id: str) -> Dict[str, Any]:
        try:
            row = db.execute(text(
                "SELECT policy FROM workout_approved_policy WHERE user_id = :uid"
            ), {"uid": user_id}).fetchone()
        except Exception:
            return dict(DEFAULT_POLICY)
        if not row or not row.policy:
            return dict(DEFAULT_POLICY)
        stored = row.policy if isinstance(row.policy, dict) else json.loads(row.policy)
        return {**DEFAULT_POLICY, **stored}

    # ────────────────────────────────────────────────────────────────────
    # Proposals (§5.5, §6.3, §11.3)
    # ────────────────────────────────────────────────────────────────────

    def _create_proposal(
        self, db: Session, user_id: str, session_id: Optional[str], *,
        kind: str, scope: Dict[str, Any], current_value: Dict[str, Any],
        proposed_value: Dict[str, Any], reason: str, evidence: Optional[Dict[str, Any]] = None,
        ttl_seconds: Optional[int] = PROPOSAL_TTL_SECONDS,
    ) -> Dict[str, Any]:
        # One live proposal per scope — a newer recommendation supersedes the
        # old one rather than queueing two answers to the same question.
        db.execute(text("""
            UPDATE workout_adjustment_proposal
            SET status = 'superseded', resolved_at = NOW()
            WHERE user_id = :uid AND status = 'pending' AND kind = :kind
              AND scope = CAST(:scope AS jsonb)
              AND (session_id = :sid OR (session_id IS NULL AND :sid IS NULL))
        """), {"uid": user_id, "kind": kind, "scope": json.dumps(scope), "sid": session_id})

        pid = str(uuid.uuid4())
        expires = (
            datetime.now(timezone.utc) + timedelta(seconds=ttl_seconds) if ttl_seconds else None
        )
        db.execute(text("""
            INSERT INTO workout_adjustment_proposal (
                id, user_id, session_id, kind, scope, current_value, proposed_value,
                reason, evidence, status, expires_at
            ) VALUES (
                :id, :uid, :sid, :kind, CAST(:scope AS jsonb), CAST(:cur AS jsonb),
                CAST(:prop AS jsonb), :reason, CAST(:ev AS jsonb), 'pending', :exp
            )
        """), {
            "id": pid, "uid": user_id, "sid": session_id, "kind": kind,
            "scope": json.dumps(scope), "cur": json.dumps(current_value),
            "prop": json.dumps(proposed_value), "reason": reason,
            "ev": json.dumps(evidence or {}, default=str), "exp": expires,
        })
        return {
            "proposal_id": pid, "session_id": session_id, "kind": kind, "scope": scope,
            "current_value": current_value, "proposed_value": proposed_value,
            "reason": reason, "evidence": evidence or {}, "status": "pending",
            "expires_at": _iso(expires),
        }

    def _maybe_propose_weight(
        self, db: Session, session: Dict[str, Any], exercises: List[Dict[str, Any]],
        ex_idx: int, rpe: int, reps: int, logged_weight: float,
    ) -> Optional[Dict[str, Any]]:
        if ex_idx >= len(exercises):
            return None
        ex = exercises[ex_idx]
        # A first-ever exercise has no prescription yet; the weight David just
        # chose is the target the recommendation is measured against.
        approved = ex.get("approved_weight") or ex.get("suggested_weight") or logged_weight
        if not approved:
            return None
        target_rpe = ex.get("rpe_target") or 8
        delta = 0
        if rpe >= int(target_rpe) + 1:
            delta = -5
        elif rpe <= int(target_rpe) - 2:
            delta = 5
        if not delta:
            return None
        return self._create_proposal(
            db, session["user_id"], session["id"],
            kind="next_set_weight",
            scope={"exercise_index": ex_idx},
            current_value={"weight": float(approved)},
            proposed_value={"weight": float(approved) + delta},
            reason=(
                "The last set was above the approved effort target."
                if delta < 0 else
                "The last set came in well under the approved effort target."
            ),
            evidence={"target_rpe": target_rpe, "reported_rpe": rpe, "completed_reps": reps},
        )

    def _approved_next_session_weights(self, db: Session, user_id: str) -> Dict[str, float]:
        """Progressions David approved out of the gym, by exercise name (§6.8).

        Newest wins if he answered the same question twice.
        """
        try:
            rows = db.execute(text("""
                SELECT scope, proposed_value FROM workout_adjustment_proposal
                WHERE user_id = :uid AND kind = 'next_session_weight' AND status = 'approved'
                ORDER BY resolved_at ASC
            """), {"uid": user_id}).fetchall()
        except Exception:
            return {}

        approved: Dict[str, float] = {}
        for r in rows:
            scope = r.scope if isinstance(r.scope, dict) else json.loads(r.scope or "{}")
            value = r.proposed_value if isinstance(r.proposed_value, dict) else json.loads(r.proposed_value or "{}")
            name, weight = scope.get("exercise"), value.get("weight")
            if name and weight is not None:
                approved[name] = float(weight)
        return approved

    def _create_next_session_proposals(self, db: Session, session: Dict[str, Any]) -> None:
        """After the workout, propose next time's weights — never apply them."""
        if not _v2_enabled():
            return
        from app.services.workout_session_service import workout_session_service as legacy
        snap = session["workout_snapshot"]
        is_deload = bool(snap.get("is_deload"))
        for ex in (snap.get("exercises") or []):
            name = legacy._effective_name(ex)
            if not name:
                continue
            try:
                suggestion = legacy._compute_suggestion(
                    session["user_id"], name, ex.get("reps", "8-10"), is_deload, db
                )
            except Exception as e:
                logger.warning(f"[WorkoutCommand] next-session suggestion failed for {name}: {e}")
                continue
            calc = suggestion.get("suggested_weight")
            approved = ex.get("approved_weight") or ex.get("suggested_weight")
            if calc is None or approved is None or float(calc) == float(approved):
                continue
            self._create_proposal(
                db, session["user_id"], None,
                kind="next_session_weight",
                scope={"exercise": name},
                current_value={"weight": float(approved)},
                proposed_value={"weight": float(calc)},
                reason=suggestion.get("progression_note") or f"Progression for {name}.",
                evidence={"last_session": suggestion.get("last_session")},
                ttl_seconds=None,
            )

    def _apply_resolve_proposal(
        self, db: Session, session: Optional[Dict[str, Any]], user_id: str,
        payload: Dict[str, Any], origin: str, command_id: str, *, approve: bool,
    ) -> Dict[str, Any]:
        pid = payload.get("proposal_id")
        if not pid:
            raise ValueError("proposal_id is required")

        row = db.execute(text("""
            SELECT id, session_id, kind, scope, current_value, proposed_value, status, expires_at
            FROM workout_adjustment_proposal
            WHERE id = :id AND user_id = :uid FOR UPDATE
        """), {"id": pid, "uid": user_id}).fetchone()
        if not row:
            raise WorkoutConflict("proposal_stale", "That recommendation no longer exists.")
        if row.status != "pending":
            return {"proposal": {"proposal_id": pid, "status": row.status}, "applied": False}
        if row.expires_at and row.expires_at < datetime.now(timezone.utc):
            db.execute(text(
                "UPDATE workout_adjustment_proposal SET status='expired', resolved_at=NOW() WHERE id=:id"
            ), {"id": pid})
            raise WorkoutConflict("proposal_stale", "That recommendation expired.")

        if not approve:
            # Rejection changes nothing but the ledger (§11.3).
            db.execute(text("""
                UPDATE workout_adjustment_proposal
                SET status='rejected', resolved_at=NOW(), resolved_by_device=:dev, approval_command_id=:cid
                WHERE id = :id
            """), {"id": pid, "dev": origin, "cid": command_id})
            return {"proposal": {"proposal_id": pid, "status": "rejected"}, "applied": False}

        applied = self._apply_proposed_value(db, session, row)

        db.execute(text("""
            UPDATE workout_adjustment_proposal
            SET status='approved', resolved_at=NOW(), resolved_by_device=:dev, approval_command_id=:cid
            WHERE id = :id
        """), {"id": pid, "dev": origin, "cid": command_id})
        return {"proposal": {"proposal_id": pid, "status": "approved"}, "applied": applied}

    def _apply_proposed_value(self, db: Session, session: Optional[Dict[str, Any]], row) -> bool:
        """Write exactly the proposed value, nothing adjacent to it (§11.3)."""
        scope = row.scope if isinstance(row.scope, dict) else json.loads(row.scope or "{}")
        proposed = row.proposed_value if isinstance(row.proposed_value, dict) else json.loads(row.proposed_value or "{}")

        if row.kind in ("next_set_weight", "exercise_weight"):
            if session is None:
                # Scoped to a live workout by exercise index; with no session
                # that index means nothing. Refuse rather than guess.
                raise WorkoutConflict(
                    "proposal_stale", "That workout is no longer running."
                )
            snap = session["workout_snapshot"]
            exercises = snap.get("exercises") or []
            idx = scope.get("exercise_index")
            if idx is None or idx < 0 or idx >= len(exercises):
                raise WorkoutConflict("proposal_stale", "That exercise is no longer in this workout.")
            weight = proposed.get("weight")
            if weight is None:
                return False
            exercises[idx]["approved_weight"] = weight
            exercises[idx]["suggested_weight"] = weight
            db.execute(text("""
                UPDATE active_workout_session SET workout_snapshot = CAST(:snap AS jsonb) WHERE id = :sid
            """), {"snap": json.dumps(snap), "sid": session["id"]})
            return True

        if row.kind == "next_session_weight":
            # Nothing to mutate in *this* session — the approval is the record,
            # and `_approved_next_session_weights` turns it into the next
            # workout's prescription (then retires it).
            return True

        logger.warning(f"[WorkoutCommand] no applicator for proposal kind {row.kind}")
        return False

    def _pending_proposal(self, db: Session, user_id: str, session_id: str) -> Optional[Dict[str, Any]]:
        try:
            row = db.execute(text("""
                SELECT id, kind, scope, current_value, proposed_value, reason, evidence, expires_at
                FROM workout_adjustment_proposal
                WHERE user_id = :uid AND session_id = :sid AND status = 'pending'
                  AND (expires_at IS NULL OR expires_at > NOW())
                ORDER BY created_at DESC LIMIT 1
            """), {"uid": user_id, "sid": session_id}).fetchone()
        except Exception:
            return None
        if not row:
            return None
        return {
            "proposal_id": row.id, "session_id": session_id, "kind": row.kind,
            "scope": row.scope, "current_value": row.current_value,
            "proposed_value": row.proposed_value, "reason": row.reason,
            "evidence": row.evidence, "status": "pending", "expires_at": _iso(row.expires_at),
        }

    def list_proposals(
        self, db: Session, user_id: str, *, status: str = "pending", limit: int = 50
    ) -> List[Dict[str, Any]]:
        rows = db.execute(text("""
            SELECT id, session_id, kind, scope, current_value, proposed_value, reason,
                   evidence, status, created_at, expires_at, resolved_at, resolved_by_device
            FROM workout_adjustment_proposal
            WHERE user_id = :uid AND status = :st
            ORDER BY created_at DESC LIMIT :lim
        """), {"uid": user_id, "st": status, "lim": limit}).fetchall()
        return [{
            "proposal_id": r.id, "session_id": r.session_id, "kind": r.kind, "scope": r.scope,
            "current_value": r.current_value, "proposed_value": r.proposed_value,
            "reason": r.reason, "evidence": r.evidence, "status": r.status,
            "created_at": _iso(r.created_at), "expires_at": _iso(r.expires_at),
            "resolved_at": _iso(r.resolved_at), "resolved_by_device": r.resolved_by_device,
        } for r in rows]

    # ────────────────────────────────────────────────────────────────────
    # Events / coaching (§5.4, §6.7)
    # ────────────────────────────────────────────────────────────────────

    def record_event(
        self, db: Session, user_id: str, session_id: str, *, kind: str, text_: str,
        after_version: Optional[int] = None, speak: bool = False, priority: str = "normal",
        proposal_id: Optional[str] = None, ttl_seconds: int = COACHING_TTL_SECONDS,
    ) -> Dict[str, Any]:
        eid = str(uuid.uuid4())
        expires = datetime.now(timezone.utc) + timedelta(seconds=ttl_seconds)
        db.execute(text("""
            INSERT INTO workout_session_event (
                id, session_id, user_id, after_version, kind, text, speak, priority,
                proposal_id, expires_at
            ) VALUES (
                :id, :sid, :uid, :ver, :kind, :text, :speak, :prio, :pid, :exp
            )
        """), {
            "id": eid, "sid": session_id, "uid": user_id, "ver": after_version,
            "kind": kind, "text": text_, "speak": speak, "prio": priority,
            "pid": proposal_id, "exp": expires,
        })
        return {
            "event_id": eid, "session_id": session_id, "after_version": after_version,
            "kind": kind, "text": text_, "speak": speak, "priority": priority,
            "expires_at": _iso(expires), "proposal_id": proposal_id,
        }

    def list_events(
        self, db: Session, session_id: str, *, after_version: Optional[int] = None, limit: int = 20
    ) -> List[Dict[str, Any]]:
        """Unexpired events for a session, oldest first.

        Expired rows are filtered rather than deleted — dropping stale coaching
        is a delivery decision (§6.7 step 6), and the history stays auditable.
        """
        sql = """
            SELECT id, after_version, kind, text, speak, priority, proposal_id, created_at, expires_at
            FROM workout_session_event
            WHERE session_id = :sid AND (expires_at IS NULL OR expires_at > NOW())
        """
        params: Dict[str, Any] = {"sid": session_id, "lim": limit}
        if after_version is not None:
            sql += " AND after_version > :ver"
            params["ver"] = after_version
        sql += " ORDER BY created_at ASC LIMIT :lim"
        rows = db.execute(text(sql), params).fetchall()
        return [{
            "event_id": r.id, "session_id": session_id, "after_version": r.after_version,
            "kind": r.kind, "text": r.text, "speak": r.speak, "priority": r.priority,
            "proposal_id": r.proposal_id, "expires_at": _iso(r.expires_at),
        } for r in rows]

    def _schedule_coaching(self, user_id: str, session_id: str, logged: Dict[str, Any]) -> None:
        """Kick off coaching generation without blocking the acknowledgement.

        Detached on purpose: the caller has already committed and returned, so
        an LLM timeout here costs a sentence, not a set.
        """
        try:
            asyncio.get_running_loop().create_task(
                self._generate_coaching(user_id, session_id, logged)
            )
        except RuntimeError:
            logger.debug("[WorkoutCommand] no running loop; skipping async coaching")

    async def _generate_coaching(self, user_id: str, session_id: str, logged: Dict[str, Any]) -> None:
        from app.db.session import SessionLocal
        from app.services.workout_session_service import workout_session_service as legacy

        db = SessionLocal()
        try:
            session = self._load_by_id(db, session_id)
            if not session or session["status"] != "active":
                return
            exercises = session["workout_snapshot"].get("exercises") or []
            entry = logged.get("logged") or {}
            ex_idx = entry.get("exercise_index") or 0
            ex = exercises[ex_idx] if 0 <= ex_idx < len(exercises) else {}
            nxt_idx = logged.get("next_exercise_index")
            feedback = await legacy._generate_set_feedback(
                exercise_name=entry.get("exercise") or "",
                set_number=entry.get("set_number") or 1,
                total_sets=ex.get("sets") or 0,
                weight=entry.get("weight") or 0,
                reps=entry.get("reps") or 0,
                rpe=entry.get("rpe"),
                suggested_weight=ex.get("approved_weight") or ex.get("suggested_weight"),
                is_last_set=bool(logged.get("exercise_complete")),
                workout_complete=bool(logged.get("workout_complete")),
                next_exercise=exercises[nxt_idx] if isinstance(nxt_idx, int) and nxt_idx < len(exercises) else None,
                rest_seconds=logged.get("rest_seconds") or 0,
            )
            policy = self.get_policy(db, user_id)
            proposal = logged.get("proposal")
            self.record_event(
                db, user_id, session_id,
                kind="set_feedback",
                text_=feedback.get("text") or "",
                after_version=session["version"],
                speak=bool(policy.get("speak_routine_coaching")),
            )
            if logged.get("pr") and policy.get("speak_prs"):
                self.record_event(
                    db, user_id, session_id, kind="pr",
                    text_=f"New personal record on {entry.get('exercise')}.",
                    after_version=session["version"], speak=True, priority="high",
                )
            if proposal:
                self.record_event(
                    db, user_id, session_id, kind="proposal",
                    text_=proposal.get("reason") or "I have a recommendation.",
                    after_version=session["version"],
                    speak=bool(policy.get("speak_proposals")),
                    priority="high", proposal_id=proposal.get("proposal_id"),
                    ttl_seconds=PROPOSAL_TTL_SECONDS,
                )
            db.commit()
        except Exception as e:
            db.rollback()
            logger.warning(f"[WorkoutCommand] coaching generation failed (non-fatal): {e}")
        finally:
            db.close()

    # ────────────────────────────────────────────────────────────────────
    # Sync / catalog / HealthKit link
    # ────────────────────────────────────────────────────────────────────

    def sync(
        self, db: Session, user_id: str, after_version: Optional[int] = None, *, compact: bool = False
    ) -> Dict[str, Any]:
        row = db.execute(text("""
            SELECT id FROM active_workout_session WHERE user_id = :uid AND status = 'active' LIMIT 1
        """), {"uid": user_id}).fetchone()
        if not row:
            return {"projection": None, "events": []}
        session = self._load_by_id(db, row.id)
        return {
            "projection": self.projection(db, session, compact=compact),
            "events": self.list_events(db, row.id, after_version=after_version),
        }

    def catalog(self, db: Session, user_id: str, limit: int = 8) -> Dict[str, Any]:
        """Compact template list the Watch caches so it can start standalone (§7.5).

        Deliberately thin: enough to render a pre-start summary, never enough
        to build a competing workout snapshot — the backend still owns that.
        """
        from app.services.training_day import is_training_day

        rows = db.execute(text("""
            SELECT id, name, exercises, scheduled_days
            FROM fitness_template
            WHERE user_id = :uid
            ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST
            LIMIT :lim
        """), {"uid": user_id, "lim": limit}).fetchall()

        templates = []
        for r in rows:
            raw = r.exercises or "[]"
            exercises = json.loads(raw) if isinstance(raw, str) else (raw or [])
            templates.append({
                "id": r.id,
                "name": r.name,
                "exercise_count": len(exercises),
                "exercises": [{
                    "name": e.get("name"),
                    "sets": e.get("sets"),
                    "reps": e.get("reps"),
                } for e in exercises[:12]],
            })

        today_template_id = None
        try:
            today = is_training_day(db, user_id, date.today())
            if isinstance(today, dict):
                today_template_id = today.get("template_id")
        except Exception as e:
            logger.debug(f"[WorkoutCommand] training-day lookup failed: {e}")

        active = db.execute(text("""
            SELECT id FROM active_workout_session WHERE user_id = :uid AND status = 'active' LIMIT 1
        """), {"uid": user_id}).fetchone()

        return {
            "schema_version": SCHEMA_VERSION,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "today_template_id": today_template_id,
            "templates": templates,
            "active_projection": (
                self.projection(db, self._load_by_id(db, active.id), compact=True) if active else None
            ),
            "policy": self.get_policy(db, user_id),
        }

    def link_healthkit(
        self, db: Session, user_id: str, session_id: str, healthkit_workout_uuid: str,
        *, activity_type: Optional[str] = None, started_at: Optional[str] = None,
        ended_at: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Bind the exact HealthKit workout to the Sara session (§6.4).

        Idempotent, and safe to call before the matching `external_workout` row
        has been ingested — the UUID is stored on the session either way, and
        ingestion picks the link up from there.
        """
        row = db.execute(text("""
            SELECT id FROM active_workout_session WHERE id = :sid AND user_id = :uid
        """), {"sid": session_id, "uid": user_id}).fetchone()
        if not row:
            raise ValueError("Session not found")

        db.execute(text("""
            UPDATE active_workout_session
            SET healthkit_workout_uuid = :hk,
                healthkit_activity_type = COALESCE(:act, healthkit_activity_type),
                healthkit_started_at = COALESCE(CAST(:st AS timestamptz), healthkit_started_at),
                healthkit_ended_at = COALESCE(CAST(:en AS timestamptz), healthkit_ended_at),
                healthkit_state = 'ended', last_device_sync_at = NOW(), updated_at = NOW()
            WHERE id = :sid
        """), {"hk": healthkit_workout_uuid, "act": activity_type,
               "st": started_at, "en": ended_at, "sid": session_id})

        linked = db.execute(text("""
            UPDATE external_workout SET sara_session_id = :sid
            WHERE user_id = :uid AND external_id = :hk AND sara_session_id IS DISTINCT FROM :sid
            RETURNING id
        """), {"sid": session_id, "uid": user_id, "hk": healthkit_workout_uuid}).fetchone()
        db.commit()
        return {"success": True, "session_id": session_id,
                "healthkit_workout_uuid": healthkit_workout_uuid,
                "external_workout_linked": bool(linked)}

    def _linked_heart_rate(
        self, db: Session, session: Dict[str, Any], hk_uuid: Optional[str]
    ) -> Optional[Dict[str, Any]]:
        """Physiology for this exact workout, by explicit link only.

        Returns None rather than guessing — the caller falls back to the legacy
        same-day heuristic, which stays until real-device parity (§16.2).
        """
        uuid_ = hk_uuid or session.get("healthkit_workout_uuid")
        if not uuid_:
            return None
        row = db.execute(text("""
            SELECT activity_type, avg_heart_rate, max_heart_rate, min_heart_rate,
                   total_energy_kcal, total_distance_m, duration_seconds
            FROM external_workout
            WHERE user_id = :uid AND external_id = :hk LIMIT 1
        """), {"uid": session["user_id"], "hk": uuid_}).fetchone()
        if not row:
            return None
        from app.services.workout_session_service import workout_session_service as legacy
        return {
            "activity": legacy._ACTIVITY_NAMES.get(str(row.activity_type), "Workout"),
            "avg_heart_rate": row.avg_heart_rate,
            "max_heart_rate": row.max_heart_rate,
            "min_heart_rate": row.min_heart_rate,
            "calories": round(float(row.total_energy_kcal)) if row.total_energy_kcal is not None else None,
            "distance_m": round(float(row.total_distance_m)) if row.total_distance_m is not None else None,
            "duration_min": round(row.duration_seconds / 60) if row.duration_seconds else None,
            "linked": True,
        }


# ────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────

def _iso(value) -> Optional[str]:
    if value is None:
        return None
    if isinstance(value, str):
        return value
    return value.isoformat()


def _v2_enabled() -> bool:
    try:
        from app.core.feature_flags import Flag, is_enabled
        return is_enabled(Flag.WORKOUT_COMMAND_V2_ENABLED)
    except Exception:
        return False


def _last_approved_weight(last_session: Optional[Dict[str, Any]]) -> Optional[float]:
    """The heaviest weight actually lifted last time for this exercise.

    That is the most recent prescription David *executed*, so it is what an
    unapproved progression is measured against.
    """
    if not last_session:
        return None
    weights = [w for w in (last_session.get("weights") or []) if w]
    if not weights:
        return None
    try:
        return float(max(weights))
    except (TypeError, ValueError):
        return None


def _exercise_view(ex: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "name": ex.get("name"),
        "variant": ex.get("variant"),
        "target_sets": ex.get("sets"),
        "target_reps": ex.get("reps"),
        "target_rpe": ex.get("rpe_target"),
        "approved_weight": ex.get("approved_weight", ex.get("suggested_weight")),
        "calculated_suggestion": ex.get("calculated_suggestion", ex.get("suggested_weight")),
        "completed_sets": ex.get("completed_sets", 0),
        "last_session": ex.get("last_session"),
        "progression_note": ex.get("progression_note"),
        "notes": ex.get("notes"),
        "metric_type": ex.get("metric_type"),
        "is_per_side": ex.get("is_per_side"),
        "superset_group": ex.get("superset_group"),
        "set_technique": ex.get("set_technique"),
        "rest_seconds": ex.get("rest_seconds"),
    }


workout_command_service = WorkoutCommandService()
