"""M1 — athlete profile, dated goals and limitations.

FITNESS_COACH_IMPLEMENTATION_PLAN Step 5 / §16 M1. Hand-written, not
autogenerated: `alembic/env.py` targets the monolith's `Base` while
`app/models/fitness_coach.py` maps on `app.db.base.Base`, so autogenerate
cannot see these tables at all. Inspect the SQL below, not a diff.

Design points that are decisions rather than mechanics:

* **Nothing has a default beyond "unknown".** No assumed novice level, no
  assumed age, no assumed sex, and no current-weight column. Bodyweight is
  an observation in `health_metric`; a copied "current weight" field starts
  disagreeing with the observations the first time a backdated correction
  lands.
* **`prefer_not_to_say` is distinct from `unknown`.** One is a refusal, the
  other is "nobody asked". A formula needing that input is skipped in both
  cases, but the athlete should not be re-asked about the first.
* **Goals use half-open `[valid_from, valid_until)`**, unlike
  `fitness_phase.end_date` which is inclusive. The conversion between the
  two conventions happens once, in the target resolver.
* **No two primary goals may overlap in time.** PostgreSQL can express that
  declaratively with an exclusion constraint over a `daterange`, which is
  what is used here — `btree_gist` is required for the `=` operator on
  `user_id` inside it. If the extension is unavailable, the constraint is
  skipped and the writer's advisory lock plus overlap check remains the
  enforcement; the migration logs that rather than failing, because an
  unavailable extension is an environment fact, not a schema error.

Revision ID: 160_fitness_athlete
Revises: 159_fitness_ownership
Create Date: 2026-10-02
"""
import logging

from alembic import op
import sqlalchemy as sa

revision = "160_fitness_athlete"
down_revision = "159_fitness_ownership"
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.runtime.migration")


def upgrade():
    bind = op.get_bind()

    bind.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS fitness_athlete_profile (
            id                        VARCHAR(36) PRIMARY KEY,
            -- Unbounded VARCHAR, matching app_user.id.
            --
            -- `app_user.id` is `character varying` with no length in the
            -- inspected schema, and real ids there run past 36 characters.
            -- Newer tables (active_workout_session, health_metric) chose
            -- VARCHAR(36) and would truncate such an id; copying that choice
            -- here makes the FK fail at insert time for exactly the athletes
            -- whose ids are longest. Match the referenced column instead.
            user_id                   VARCHAR NOT NULL UNIQUE
                                          REFERENCES app_user(id) ON DELETE CASCADE,
            height_cm                 NUMERIC(6,2),
            date_of_birth             DATE,
            calculation_sex           VARCHAR(24) NOT NULL DEFAULT 'unknown',
            training_experience_years NUMERIC(5,2),
            training_level            VARCHAR(20) NOT NULL DEFAULT 'unknown',
            timezone                  VARCHAR(64) NOT NULL DEFAULT 'America/New_York',
            weight_unit               VARCHAR(8)  NOT NULL DEFAULT 'lb',
            length_unit               VARCHAR(8)  NOT NULL DEFAULT 'in',
            available_days            JSONB NOT NULL DEFAULT '[]'::jsonb,
            preferred_duration_minutes INTEGER,
            equipment                 JSONB NOT NULL DEFAULT '[]'::jsonb,
            -- canonical exercise_library ids, not names: a name-keyed
            -- exclusion stops working the moment the athlete renames it
            preferred_exercise_ids    JSONB NOT NULL DEFAULT '[]'::jsonb,
            excluded_exercise_ids     JSONB NOT NULL DEFAULT '[]'::jsonb,
            dietary_restrictions      JSONB NOT NULL DEFAULT '[]'::jsonb,
            dietary_preferences       JSONB NOT NULL DEFAULT '[]'::jsonb,
            supplements               JSONB NOT NULL DEFAULT '[]'::jsonb,
            coaching_style            VARCHAR(20) NOT NULL DEFAULT 'unset',
            monitoring_consent        BOOLEAN NOT NULL DEFAULT FALSE,
            row_version               INTEGER NOT NULL DEFAULT 1,
            created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),

            CONSTRAINT ck_athlete_profile_sex CHECK (
                calculation_sex IN ('male','female','unknown','prefer_not_to_say')),
            CONSTRAINT ck_athlete_profile_level CHECK (
                training_level IN ('unknown','novice','intermediate','advanced')),
            CONSTRAINT ck_athlete_profile_height CHECK (
                height_cm IS NULL OR (height_cm > 50 AND height_cm < 275)),
            CONSTRAINT ck_athlete_profile_experience CHECK (
                training_experience_years IS NULL OR
                (training_experience_years >= 0 AND training_experience_years <= 90)),
            CONSTRAINT ck_athlete_profile_version CHECK (row_version >= 1)
        )
    """))

    bind.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS fitness_athlete_profile_change (
            id           VARCHAR(36) PRIMARY KEY,
            user_id      VARCHAR NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
            field        VARCHAR(64) NOT NULL,
            old_value    JSONB,
            new_value    JSONB,
            from_version INTEGER NOT NULL,
            to_version   INTEGER NOT NULL,
            changed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            source       VARCHAR(32) NOT NULL DEFAULT 'user'
        )
    """))
    bind.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_athlete_profile_change_user_time
        ON fitness_athlete_profile_change (user_id, changed_at DESC)
    """))

    bind.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS fitness_athlete_goal (
            id                       VARCHAR(36) PRIMARY KEY,
            user_id                  VARCHAR NOT NULL
                                         REFERENCES app_user(id) ON DELETE CASCADE,
            kind                     VARCHAR(24) NOT NULL,
            is_primary               BOOLEAN NOT NULL DEFAULT TRUE,
            priority                 INTEGER NOT NULL DEFAULT 1,
            rationale                TEXT,
            target_weight_kg         NUMERIC(6,2),
            -- which rate the athlete actually chose; storing both and
            -- inferring later makes 0.25 kg/week and 0.3%/week
            -- indistinguishable after any bodyweight change
            rate_basis               VARCHAR(12) NOT NULL DEFAULT 'none',
            target_rate_kg_week      NUMERIC(6,3),
            target_rate_percent_week NUMERIC(6,3),
            strength_targets         JSONB NOT NULL DEFAULT '{}'::jsonb,
            valid_from               DATE NOT NULL,
            valid_until              DATE,
            recorded_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            supersedes_id            VARCHAR(36)
                                         REFERENCES fitness_athlete_goal(id) ON DELETE SET NULL,
            source                   VARCHAR(32) NOT NULL DEFAULT 'user',
            approved_at              TIMESTAMPTZ,

            CONSTRAINT ck_athlete_goal_kind CHECK (kind IN (
                'hypertrophy','strength','powerbuilding','gain','cut',
                'recomp','maintenance')),
            CONSTRAINT ck_athlete_goal_rate_basis CHECK (
                rate_basis IN ('absolute','percent','none')),
            CONSTRAINT ck_athlete_goal_interval CHECK (
                valid_until IS NULL OR valid_until > valid_from),
            CONSTRAINT ck_athlete_goal_priority CHECK (priority BETWEEN 1 AND 10),
            CONSTRAINT ck_athlete_goal_target_weight CHECK (
                target_weight_kg IS NULL OR
                (target_weight_kg > 0 AND target_weight_kg < 500)),
            CONSTRAINT ck_athlete_goal_rate_coherent CHECK (
                (rate_basis = 'absolute' AND target_rate_kg_week IS NOT NULL
                     AND target_rate_percent_week IS NULL)
                OR (rate_basis = 'percent' AND target_rate_percent_week IS NOT NULL
                     AND target_rate_kg_week IS NULL)
                OR (rate_basis = 'none' AND target_rate_kg_week IS NULL
                     AND target_rate_percent_week IS NULL)),
            CONSTRAINT ck_athlete_goal_cut_sign CHECK (
                NOT (kind = 'cut' AND
                     COALESCE(target_rate_kg_week, target_rate_percent_week, 0) > 0)),
            CONSTRAINT ck_athlete_goal_gain_sign CHECK (
                NOT (kind = 'gain' AND
                     COALESCE(target_rate_kg_week, target_rate_percent_week, 0) < 0))
        )
    """))
    bind.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_athlete_goal_user_from
        ON fitness_athlete_goal (user_id, valid_from DESC)
    """))
    bind.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_athlete_goal_user_primary
        ON fitness_athlete_goal (user_id, valid_from DESC)
        WHERE is_primary
    """))

    # One primary goal may be in force on any given day. `daterange` with an
    # open upper bound models "still current" exactly, and `&&` is the
    # overlap test — this is the one constraint that cannot be a CHECK,
    # because it is about the relationship between rows.
    try:
        bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS btree_gist"))
        bind.execute(sa.text("""
            DO $$ BEGIN
                ALTER TABLE fitness_athlete_goal
                ADD CONSTRAINT ex_athlete_goal_primary_no_overlap
                EXCLUDE USING gist (
                    user_id WITH =,
                    daterange(valid_from, valid_until, '[)') WITH &&
                ) WHERE (is_primary);
            EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$
        """))
    except Exception as exc:  # pragma: no cover - environment-dependent
        # An unavailable extension is an environment fact, not a schema
        # error. The writer in services/fitness/profile.py takes a per-user
        # advisory lock and checks overlap itself, so correctness does not
        # depend on this constraint — it is defence in depth.
        logger.warning(
            "btree_gist unavailable; primary-goal overlap is enforced only by "
            "the application writer's advisory lock: %s", exc
        )

    bind.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS fitness_athlete_limitation (
            id                     VARCHAR(36) PRIMARY KEY,
            user_id                VARCHAR NOT NULL
                                       REFERENCES app_user(id) ON DELETE CASCADE,
            area                   VARCHAR(120) NOT NULL,
            description            TEXT,
            excluded_exercise_ids  JSONB NOT NULL DEFAULT '[]'::jsonb,
            modified_exercise_ids  JSONB NOT NULL DEFAULT '[]'::jsonb,
            -- coarse and self-reported. There is deliberately NO diagnosis
            -- column: "right shoulder hurts overhead" is data, "impingement"
            -- is a clinical conclusion this system does not draw.
            severity_flag          VARCHAR(12),
            effective_from         DATE NOT NULL,
            effective_until        DATE,
            status                 VARCHAR(16) NOT NULL DEFAULT 'active',
            notes                  TEXT,
            created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),

            CONSTRAINT ck_athlete_limitation_status CHECK (
                status IN ('active','resolved','superseded')),
            CONSTRAINT ck_athlete_limitation_severity CHECK (
                severity_flag IS NULL OR
                severity_flag IN ('mild','moderate','severe')),
            CONSTRAINT ck_athlete_limitation_interval CHECK (
                effective_until IS NULL OR effective_until > effective_from)
        )
    """))
    bind.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_athlete_limitation_user_status
        ON fitness_athlete_limitation (user_id, status)
    """))
    bind.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_athlete_limitation_user_dates
        ON fitness_athlete_limitation (user_id, effective_from, effective_until)
    """))


def downgrade():
    bind = op.get_bind()
    for stmt in (
        "DROP INDEX IF EXISTS ix_athlete_limitation_user_dates",
        "DROP INDEX IF EXISTS ix_athlete_limitation_user_status",
        "DROP TABLE IF EXISTS fitness_athlete_limitation",
        "DROP INDEX IF EXISTS ix_athlete_goal_user_primary",
        "DROP INDEX IF EXISTS ix_athlete_goal_user_from",
        "DROP TABLE IF EXISTS fitness_athlete_goal",
        "DROP INDEX IF EXISTS ix_athlete_profile_change_user_time",
        "DROP TABLE IF EXISTS fitness_athlete_profile_change",
        "DROP TABLE IF EXISTS fitness_athlete_profile",
    ):
        bind.execute(sa.text(stmt))
