/**
 * Step 22 of FITNESS_COACH_IMPLEMENTATION_PLAN: a review is readable and a
 * change is decidable, entirely outside chat.
 *
 * The claims being pinned, each for a concrete reason:
 *
 * - **Nothing is generated by opening the tab.** Navigation is not consent,
 *   and a model call costs a minute of GPU time on the lane chat shares.
 * - **The status machine is rendered as itself.** `insufficient_data` is a
 *   complete answer whose remedy is to log more; rendering it as a failure
 *   invites a retry that cannot help.
 * - **Blockers appear before the Accept button.** A button that 409s is
 *   worse than one that is not there.
 * - **Accept and Reject are separate**, and accepting shows the old → new
 *   numbers first. A single toggle makes "not decided" and "declined" the
 *   same state.
 * - **Acceptance invalidates the targets**, so the Overview and the legacy
 *   dashboard cannot keep showing the old calories.
 * - **A superseded review still shows what it said.**
 * - **There is no citation UI**, because there is no library behind one.
 */
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import React from 'react'
import { beforeEach, describe, expect, it, vi } from 'vitest'

import CoachReviews from '../CoachReviews'
import type {
  CoachRecommendation,
  CoachReview,
  CoachReviewDetail,
  RecommendationPreview,
} from '../../../types/fitnessCoach'

const ATHLETE = 'athlete-coach'

vi.mock('../../../stores/authStore', () => ({
  useAuthStore: (selector: (s: unknown) => unknown) =>
    selector({ user: { id: ATHLETE, email: 'a@example.invalid' } }),
}))

function review(over: Partial<CoachReview> = {}): CoachReview {
  return {
    id: 'rev-1', user_id: ATHLETE, kind: 'weekly',
    period: { start: '2026-09-21', end: '2026-09-28' },
    status: 'complete', input_hash: 'abc',
    state_schema_version: 1, analytics_version: 1,
    data_revision: 'rev-1', collected_at: '2026-09-28T12:00:00Z',
    source_cutoff: null, model_requested: 'qwen3.8-27b',
    model_actual: 'qwen3.8-27b', provider: 'local',
    prompt_version: 'fitness_coach_review_v1', prompt_hash: 'h'.repeat(64),
    output_schema_version: 1,
    summary: 'Weight is flat against a cut over 6 of 7 logged days.',
    evidence_refs: [], error_category: null, error_detail: null,
    run_id: null, attempt: 1, revision: 1,
    supersedes_id: null, superseded_by_id: null,
    requested_by: 'user', evaluated_at: '2026-09-28T12:01:00Z',
    created_at: '2026-09-28T12:00:30Z',
    ...over,
  }
}

function recommendation(over: Partial<CoachRecommendation> = {}): CoachRecommendation {
  return {
    id: 'rec-1', review_id: 'rev-1', user_id: ATHLETE,
    category: 'nutrition_change', action: 'target_revision',
    title: 'Drop calories by 150',
    rationale: 'Flat for a week against a cut target over 6 of 7 logged days.',
    confidence: 'moderate',
    confidence_basis: 'six of seven days have a weigh-in',
    limitations: 'One day has no weigh-in.',
    metric_paths: ['weight.velocity_weekly'], evidence_refs: [],
    proposed_change: {
      kind: 'target_revision', scope: 'default',
      effective_date: '2026-09-29',
      target_values: {
        calories: 2850, protein_g: 200, carbs_g: null, fat_g: null,
        sleep_hours: null, water_ml: null, steps: null,
        calorie_tolerance_pct: 10, protein_tolerance_pct: 10,
      },
    },
    current_target_revision_id: 'trev-1', current_phase_id: null,
    expires_at: '2026-10-12T12:00:00Z',
    decision_status: 'proposed', decided_at: null, decided_by: null,
    decision_note: null, action_receipt_id: null, applied_revision_id: null,
    priority: 1, created_at: '2026-09-28T12:01:00Z',
    ...over,
  }
}

function detail(over: Partial<CoachReviewDetail> = {}): CoachReviewDetail {
  return {
    ...review(),
    input_state: {
      schema_version: 1, analytics_version: 1, user_id: ATHLETE,
      as_of: '2026-09-28T12:00:00Z', athlete_local_date: '2026-09-28',
      timezone: 'America/New_York',
      period: { start: '2026-09-21', end: '2026-09-28' },
      freshness: 'fresh', data_revision: 'rev-1',
      profile: null, goals: [], limitations: [], targets: null, program: {},
      sections: {
        weight: {
          section: 'weight',
          metrics: {
            velocity_weekly: {
              key: 'weight.velocity_weekly', value: -0.05, unit: 'kg/week',
              observed_days: 6, expected_days: 7, source_count: 6,
              quality_flags: [], analytics_version: 1,
            },
            trend_slope_weekly: {
              key: 'weight.trend_slope_weekly', value: null,
              unit: 'kg/week', unavailable_reason: 'insufficient_coverage',
              observed_days: 6, expected_days: 28, source_count: 6,
              quality_flags: [], analytics_version: 1,
            },
          },
          items: [], limitations: [],
        },
      },
      quality: {
        observed_weight_days: 6, expected_weight_days: 7, sleep_nights: 6,
        nutrition_complete_days: 5, nutrition_partial_days: 1,
        nutrition_unknown_days: 1,
        missing_fields: ['weight.trend_slope_weekly: insufficient_coverage'],
        unresolved_units: 0, unresolved_exercise_identities: 0,
        source_conflicts: 0, incomplete_workouts: 0, overdue_cadences: [],
        stale_profile: false, no_effective_target: false,
        insufficient_comparable_exposures: [], notes: [],
      },
      recent_changes: [], evidence_refs: [], degraded_dependencies: [],
    },
    output: {
      output_version: 1,
      summary: 'Weight is flat against a cut over 6 of 7 logged days.',
      coaching_priority: 'Decide on a small calorie adjustment.',
      observations: [{
        text: 'Weekly change was -0.05 kg/week.',
        metric_paths: ['weight.velocity_weekly'],
      }],
      limitations: ['One day has no weigh-in.'],
      confidence: 'moderate',
      confidence_basis: 'six of seven days have a weigh-in',
      recommendations: [],
    },
    recommendations: [recommendation()],
    ...over,
  }
}

function previewOf(over: Partial<RecommendationPreview> = {}): RecommendationPreview {
  return {
    recommendation: recommendation(),
    applicable: true, acceptable: true,
    changes: [
      { field: 'calories', current: 3000, proposed: 2850, delta: -150, unit: 'kcal', is_change: true },
      { field: 'protein_g', current: 200, proposed: 200, delta: 0, unit: 'g', is_change: false },
    ],
    scope: 'default', effective_date: '2026-09-29',
    proposed_against_revision_id: 'trev-1', latest_revision_id: 'trev-1',
    stale: false, expired: false, blockers: [],
    coverage: {
      observed_weight_days: 6, expected_weight_days: 7,
      nutrition_complete_days: 5, sleep_nights: 6,
      period_start: '2026-09-21', period_end: '2026-09-28',
    },
    limitations: ['One day has no weigh-in.'],
    ...over,
  }
}

interface Call { url: string; method: string }

let calls: Call[] = []
let reviewList: CoachReview[] = []
let reviewDetail: CoachReviewDetail | null = null
let previewBody: RecommendationPreview = previewOf()
let previewStatus = 200
let acceptStatus = 200
let acceptBody: unknown = {}
let requestStatus = 202
let requestBody: unknown = review()
let chainBody: CoachReview[] = []

function stubFetch() {
  globalThis.fetch = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = String(input)
    const method = (init?.method ?? 'GET').toUpperCase()
    calls.push({ url, method })
    const json = (status: number, body: unknown) =>
      new Response(JSON.stringify(body), {
        status, headers: { 'Content-Type': 'application/json' },
      })

    if (url.includes('/coach/reviews') && method === 'POST') {
      return json(requestStatus, requestBody)
    }
    if (url.match(/\/coach\/reviews\/[^/]+\/chain/)) {
      return json(200, chainBody)
    }
    if (url.match(/\/coach\/reviews\/[^/?]+/) && method === 'GET') {
      return reviewDetail
        ? json(200, reviewDetail)
        : json(404, { detail: 'Review not found' })
    }
    if (url.includes('/coach/reviews') && method === 'GET') {
      return json(200, reviewList)
    }
    if (url.includes('/preview')) {
      return json(previewStatus, previewBody)
    }
    if (url.includes('/accept')) {
      return json(acceptStatus, acceptBody)
    }
    if (url.includes('/reject')) {
      return json(200, recommendation({
        decision_status: 'rejected', decided_at: '2026-09-28T13:00:00Z',
        decided_by: 'user',
      }))
    }
    return json(200, {})
  }) as unknown as typeof fetch
}

function wrap(ui: React.ReactElement) {
  const client = new QueryClient({
    defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
  })
  return render(<QueryClientProvider client={client}>{ui}</QueryClientProvider>)
}

beforeEach(() => {
  calls = []
  reviewList = [review()]
  reviewDetail = detail()
  previewBody = previewOf()
  previewStatus = 200
  acceptStatus = 200
  acceptBody = {
    recommendation: recommendation({
      decision_status: 'accepted', decided_at: '2026-09-28T13:00:00Z',
      decided_by: 'user', action_receipt_id: 'receipt-abcdef12',
      applied_revision_id: 'trev-2abcdef',
    }),
    action_receipt_id: 'receipt-abcdef12',
    applied_revision_id: 'trev-2abcdef',
    message: 'Applied from 2026-09-29: 2850 kcal, 200 g protein (default scope, revision 2).',
    duplicate: false,
  }
  requestStatus = 202
  requestBody = review({ id: 'rev-new', status: 'pending', summary: null })
  chainBody = [review()]
  stubFetch()
})

// ── Nothing happens by arriving ───────────────────────────────────────────

describe('requesting', () => {
  it('generates nothing just by opening the tab', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('coach-reviews')).toBeTruthy())
    expect(calls.filter((c) => c.method === 'POST')).toHaveLength(0)
  })

  it('says plainly that nothing changes without an acceptance', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('coach-reviews')).toBeTruthy())
    expect(screen.getByTestId('coach-reviews').textContent).toContain(
      'Nothing changes until you accept',
    )
  })

  it('requests a review only when asked', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('request-review')).toBeTruthy())
    await userEvent.click(screen.getByTestId('request-review'))
    await waitFor(() =>
      expect(calls.some((c) => c.method === 'POST' && c.url.includes('/reviews')))
        .toBe(true),
    )
  })

  it('offers a forced rerun when one already exists for the period', async () => {
    // A rerun keeps the old review, so this is an offer rather than an
    // overwrite — and it is the caller's decision because it costs a model
    // call.
    requestStatus = 409
    requestBody = {
      detail: {
        code: 'review_exists',
        message:
          'a review of this period exists but the data has changed since; ' +
          'request again with force=true to produce a linked revision',
        review_id: 'rev-1', status: 'complete',
      },
    }
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('request-review')).toBeTruthy())
    await userEvent.click(screen.getByTestId('request-review'))

    await waitFor(() => expect(screen.getByTestId('force-review')).toBeTruthy())
    expect(screen.getByTestId('force-review').textContent).toContain(
      'keeps the old review',
    )
  })

  it('tells the person when there are no reviews, and why', async () => {
    reviewList = []
    reviewDetail = null
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('no-reviews')).toBeTruthy())
    expect(screen.getByTestId('no-reviews').textContent).toContain(
      'only produced when you ask',
    )
  })
})

// ── The status machine ────────────────────────────────────────────────────

describe('status', () => {
  it('shows a queued review as queued, not as empty', async () => {
    reviewList = [review({ status: 'pending', summary: null })]
    reviewDetail = detail({ status: 'pending', summary: null, output: null })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('review-in-flight')).toBeTruthy())
    expect(screen.getByTestId('review-in-flight').textContent).toContain('Queued')
    expect(screen.getByTestId('review-in-flight').textContent).toContain(
      'Nothing about your plan changes while this runs',
    )
  })

  it('shows a running review as thinking', async () => {
    reviewList = [review({ status: 'running', summary: null })]
    reviewDetail = detail({ status: 'running', summary: null, output: null })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('review-in-flight')).toBeTruthy())
    expect(screen.getByTestId('review-in-flight').textContent).toContain('Thinking')
  })

  it('renders insufficient data as a complete answer, not a failure', async () => {
    reviewList = [review({
      status: 'insufficient_data', summary: null,
      error_category: 'insufficient_data',
      error_detail: 'Two independent streams with at least two days each are needed.',
    })]
    reviewDetail = detail({
      status: 'insufficient_data', summary: null, output: null,
      error_category: 'insufficient_data',
      error_detail: 'Two independent streams with at least two days each are needed.',
      recommendations: [],
    })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('review-insufficient')).toBeTruthy())

    const block = screen.getByTestId('review-insufficient')
    expect(block.textContent).toContain('Log a few more days')
    expect(block.textContent).toContain('complete answer, not a failure')
    expect(screen.queryByTestId('review-failed')).toBeNull()
    // And the detail from the backend is shown, so "what exactly is missing"
    // is answerable.
    expect(screen.getByTestId('insufficient-detail').textContent).toContain(
      'two days each',
    )
  })

  it('explains a failure in plain language and says nothing was saved', async () => {
    reviewList = [review({ status: 'failed', summary: null, error_category: 'model_timeout' })]
    reviewDetail = detail({
      status: 'failed', summary: null, output: null,
      error_category: 'model_timeout', recommendations: [],
    })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('review-failed')).toBeTruthy())
    const block = screen.getByTestId('review-failed')
    expect(block.textContent).toContain('took too long')
    expect(block.textContent).toContain('none of your logged data was')
  })

  it('explains a safety rejection without showing what was rejected', async () => {
    // The rejected text is not stored and must not be rendered: shipping it
    // with a caveat is still shipping it.
    reviewList = [review({ status: 'failed', error_category: 'safety_refused' })]
    reviewDetail = detail({
      status: 'failed', summary: null, output: null,
      error_category: 'safety_refused', recommendations: [],
    })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('review-failed')).toBeTruthy())
    expect(screen.getByTestId('review-failed').textContent).toContain(
      'rejected rather than shown to you',
    )
  })

  it('explains an ungrounded claim as a rejection, not a model opinion', async () => {
    reviewList = [review({ status: 'failed', error_category: 'ungrounded_claim' })]
    reviewDetail = detail({
      status: 'failed', summary: null, output: null,
      error_category: 'ungrounded_claim', recommendations: [],
    })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('review-failed')).toBeTruthy())
    expect(screen.getByTestId('review-failed').textContent).toContain(
      'not in your data',
    )
  })
})

// ── Reasoning and coverage, without raw JSON ──────────────────────────────

describe('reading a review', () => {
  it('shows the cited figures as they stood in the snapshot', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('observations')).toBeTruthy())
    const cited = screen.getByTestId('cited-weight.velocity_weekly')
    expect(cited.textContent).toContain('-0.05')
    expect(cited.textContent).toContain('6 of 7 days')
  })

  it('shows complete and partial logging days separately', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('coverage')).toBeTruthy())
    const coverage = screen.getByTestId('coverage')
    expect(coverage.textContent).toContain('6 of 7 days')
    expect(coverage.textContent).toContain('5 days')
    expect(coverage.textContent).toContain('6 nights')
  })

  it('lists what the review could not know', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('unavailable-list')).toBeTruthy())
    const block = screen.getByTestId('unavailable-list')
    expect(block.textContent).toContain('weight.trend_slope_weekly')
    expect(block.textContent).toContain('insufficient coverage')
  })

  it('shows the limitations the review stated', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('limitations')).toBeTruthy())
    expect(screen.getByTestId('limitations').textContent).toContain(
      'no weigh-in',
    )
  })

  it('names the model that actually answered', async () => {
    // A fallback that answered as the primary makes every comparison between
    // runs meaningless, so the actual model is on the screen.
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('review-meta')).toBeTruthy())
    const meta = screen.getByTestId('review-meta')
    expect(meta.textContent).toContain('qwen3.8-27b')
    expect(meta.textContent).toContain('fitness_coach_review_v1')
    expect(meta.textContent).toContain('analytics v1')
  })

  it('keeps confidence and coverage as separate statements', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('review-confidence')).toBeTruthy())
    expect(screen.getByTestId('review-confidence').textContent).toContain(
      'moderate confidence',
    )
    expect(screen.getByTestId('review-confidence').textContent).toContain(
      'six of seven days',
    )
  })

  it('renders no citation affordance at all', async () => {
    // There is no curated library yet, so a citation box is a place for a
    // fabricated reference to sit.
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('review-detail')).toBeTruthy())
    const text = screen.getByTestId('review-detail').textContent ?? ''
    expect(text.toLowerCase()).not.toContain('citation')
    expect(text.toLowerCase()).not.toContain('et al')
    expect(screen.queryByText(/stud(y|ies)/i)).toBeNull()
  })

  it('keeps a superseded review readable and says why it is kept', async () => {
    reviewList = [
      review({ id: 'rev-2', revision: 2 }),
      review({ id: 'rev-1', superseded_by_id: 'rev-2' }),
    ]
    reviewDetail = detail({ superseded_by_id: 'rev-2' })
    chainBody = [review(), review({ id: 'rev-2', revision: 2 })]
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('superseded-note')).toBeTruthy())
    expect(screen.getByTestId('superseded-note').textContent).toContain(
      'correct reading of the data it had',
    )
    expect(screen.getByTestId('review-chain').textContent).toContain(
      '2 revisions',
    )
  })

  it('marks a revision in the list', async () => {
    reviewList = [review({ id: 'rev-2', revision: 3 })]
    reviewDetail = detail({ id: 'rev-2', revision: 3 })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('revision-badge')).toBeTruthy())
    expect(screen.getByTestId('revision-badge').textContent).toContain('revision 3')
  })
})

// ── Deciding ──────────────────────────────────────────────────────────────

describe('deciding', () => {
  async function openPreview() {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('rec-expand')).toBeTruthy())
    await userEvent.click(screen.getByTestId('rec-expand'))
    await waitFor(() => expect(screen.getByTestId('change-table')).toBeTruthy())
  }

  it('shows the old and new numbers before offering Accept', async () => {
    await openPreview()
    const row = screen.getByTestId('change-calories')
    expect(row.textContent).toContain('3000')
    expect(row.textContent).toContain('2850')
    expect(row.textContent).toContain('-150')
    expect(screen.getByTestId('effective-date').textContent).toContain('2026-09-29')
  })

  it('shows unchanged fields too, so the diff is the whole proposal', async () => {
    await openPreview()
    expect(screen.getByTestId('change-protein_g').textContent).toContain('200')
  })

  it('offers Accept and Reject as separate actions', async () => {
    await openPreview()
    expect(screen.getByTestId('rec-accept')).toBeTruthy()
    expect(screen.getByTestId('rec-reject')).toBeTruthy()
  })

  it('does not request a preview until asked', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('rec-expand')).toBeTruthy())
    expect(calls.some((c) => c.url.includes('/preview'))).toBe(false)
  })

  it('confirms an acceptance with the committed numbers', async () => {
    await openPreview()
    await userEvent.click(screen.getByTestId('rec-accept'))
    await waitFor(() => expect(screen.getByTestId('decision-banner')).toBeTruthy())
    const banner = screen.getByTestId('decision-banner')
    expect(banner.textContent).toContain('2850 kcal')
    expect(banner.textContent).toContain('2026-09-29')
  })

  it('invalidates the targets after an acceptance', async () => {
    // Otherwise the Overview and the legacy dashboard keep showing the old
    // calories until a reload — the exact two-answers condition Step 18 closed.
    await openPreview()
    const before = calls.length
    await userEvent.click(screen.getByTestId('rec-accept'))
    await waitFor(() => expect(screen.getByTestId('decision-banner')).toBeTruthy())
    await waitFor(() =>
      expect(
        calls.slice(before).some((c) =>
          c.method === 'GET' && c.url.includes('/coach/reviews')),
      ).toBe(true),
    )
  })

  it('records a rejection and changes nothing', async () => {
    await openPreview()
    await userEvent.click(screen.getByTestId('rec-reject'))
    await waitFor(() => expect(screen.getByTestId('decision-banner')).toBeTruthy())
    expect(screen.getByTestId('decision-banner').textContent).toContain(
      'nothing changed',
    )
    expect(calls.some((c) => c.url.includes('/accept'))).toBe(false)
  })

  it('shows an already-decided recommendation with its receipt', async () => {
    reviewDetail = detail({
      recommendations: [recommendation({
        decision_status: 'accepted', decided_at: '2026-09-28T13:00:00Z',
        decided_by: 'user', action_receipt_id: 'receipt-abcdef12',
        applied_revision_id: 'trev-2abcdef',
      })],
    })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('rec-receipt')).toBeTruthy())
    const receipt = screen.getByTestId('rec-receipt')
    expect(receipt.textContent).toContain('Applied')
    expect(receipt.textContent).toContain('trev-2ab')
    expect(receipt.textContent).toContain('receipt-')
    // And no Accept button on a decided row.
    expect(screen.queryByTestId('rec-accept')).toBeNull()
  })

  it('shows a rejected recommendation with its note', async () => {
    reviewDetail = detail({
      recommendations: [recommendation({
        decision_status: 'rejected', decided_at: '2026-09-28T13:00:00Z',
        decided_by: 'user', decision_note: 'not this week',
      })],
    })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('rec-decision')).toBeTruthy())
    expect(screen.getByTestId('recommendation-rec-1').textContent).toContain(
      'not this week',
    )
  })
})

// ── Blockers ──────────────────────────────────────────────────────────────

describe('blockers', () => {
  async function openPreview() {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('rec-expand')).toBeTruthy())
    await userEvent.click(screen.getByTestId('rec-expand'))
    await waitFor(() => expect(screen.getByTestId('rec-blockers')).toBeTruthy())
  }

  it('disables Accept for a stale proposal and says to re-run', async () => {
    previewBody = previewOf({
      acceptable: false, stale: true, latest_revision_id: 'trev-9',
      blockers: [
        'the targets have changed since this was proposed, so accepting it ' +
        'would apply an old comparison over a newer decision',
      ],
    })
    await openPreview()
    expect(screen.getByTestId('rec-accept')).toBeDisabled()
    expect(screen.getByTestId('rec-blockers').textContent).toContain(
      'newer decision',
    )
    expect(screen.getByTestId('rec-blockers').textContent).toContain(
      'Ask for a new review',
    )
  })

  it('disables Accept for an expired proposal', async () => {
    previewBody = previewOf({
      acceptable: false, expired: true,
      blockers: ['this proposal has expired'],
    })
    await openPreview()
    expect(screen.getByTestId('rec-accept')).toBeDisabled()
  })

  it('keeps an unsupported action as advice and never as a hidden apply', async () => {
    // The completion criterion. A greyed-out button with no explanation reads
    // as a bug; this says what to do instead.
    previewBody = previewOf({
      recommendation: recommendation({ action: 'program_change' }),
      applicable: false, acceptable: false, changes: [],
      blockers: [
        'a program_change proposal cannot be applied automatically yet; it ' +
        'is advice to act on by hand',
      ],
    })
    await openPreview()
    expect(screen.getByTestId('rec-accept')).toBeDisabled()
    expect(screen.getByTestId('advice-only').textContent).toContain(
      'plan editor',
    )
  })

  it('offers no Accept at all when the preview could not be read', async () => {
    // A read failure is not permission to proceed on last-known state.
    previewStatus = 500
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('rec-expand')).toBeTruthy())
    await userEvent.click(screen.getByTestId('rec-expand'))
    await waitFor(() => expect(screen.getByTestId('preview-error')).toBeTruthy())
    expect(screen.queryByTestId('rec-accept')).toBeNull()
    expect(screen.getByTestId('preview-error').textContent).toContain(
      'Nothing has happened',
    )
  })

  it('surfaces a conflict raised at accept time and re-checks', async () => {
    // The preview can go stale between rendering and pressing — the athlete
    // may have edited their targets on another device.
    acceptStatus = 409
    acceptBody = {
      detail: {
        code: 'stale_target',
        message: 'the targets have changed since this was proposed',
        recommendation_id: 'rec-1',
        current: { latest_revision_id: 'trev-9' },
        remedy: 'request a new review for the current period',
      },
    }
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('rec-expand')).toBeTruthy())
    await userEvent.click(screen.getByTestId('rec-expand'))
    await waitFor(() => expect(screen.getByTestId('rec-accept')).toBeTruthy())

    const previewCalls = calls.filter((c) => c.url.includes('/preview')).length
    await userEvent.click(screen.getByTestId('rec-accept'))

    await waitFor(() => expect(screen.getByTestId('rec-error')).toBeTruthy())
    expect(screen.getByTestId('rec-error').textContent?.toLowerCase())
      .toContain('changed')
    // And it re-checks rather than leaving a stale Accept button armed.
    await waitFor(() =>
      expect(calls.filter((c) => c.url.includes('/preview')).length)
        .toBeGreaterThan(previewCalls),
    )
  })

  it('does not auto-accept when the preview is merely opened', async () => {
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('rec-expand')).toBeTruthy())
    await userEvent.click(screen.getByTestId('rec-expand'))
    await waitFor(() => expect(screen.getByTestId('change-table')).toBeTruthy())
    expect(calls.some((c) => c.url.includes('/accept'))).toBe(false)
  })

  it('renders a no-change proposal as recording agreement', async () => {
    previewBody = previewOf({
      recommendation: recommendation({ action: 'none', category: 'maintain' }),
      changes: [],
    })
    wrap(<CoachReviews />)
    await waitFor(() => expect(screen.getByTestId('rec-expand')).toBeTruthy())
    await userEvent.click(screen.getByTestId('rec-expand'))
    await waitFor(() => expect(screen.getByTestId('no-change')).toBeTruthy())
    expect(screen.getByTestId('no-change').textContent).toContain(
      'changes no numbers',
    )
  })
})

// ── Account scoping ───────────────────────────────────────────────────────

describe('scoping', () => {
  it('scopes every request to the signed-in athlete', async () => {
    // Query caches live across an account change; a key without the user id
    // would hand the next person who signs in the previous one's review.
    const { fitnessKeys } = await import('../../../hooks/useFitnessCoach')
    expect(fitnessKeys.reviews('alice')).toContain('alice')
    expect(fitnessKeys.review('alice', 'rev-1')).toContain('alice')
    expect(fitnessKeys.recommendationPreview('alice', 'rec-1')).toContain('alice')
    expect(fitnessKeys.reviews('alice')).not.toEqual(fitnessKeys.reviews('bob'))
  })
})
