/**
 * Fitness → Coach: read a review, see what it reasoned from, decide.
 *
 * FITNESS_COACH_IMPLEMENTATION_PLAN Step 22. Completion criteria: review and
 * acceptance are fully operable outside chat; evidence, coverage and
 * rationale are readable without raw JSON; unsupported actions stay advice
 * rather than hidden execution.
 *
 * Six rules the UI follows, each for a concrete reason:
 *
 * 1. **Requesting a review is explicit.** No review is generated by opening
 *    this tab. Navigation is not consent, and a model call costs a minute of
 *    GPU time on the lane chat shares.
 * 2. **Accept and Reject are separate buttons**, and accepting shows the
 *    old → new numbers first. A single "apply" toggle makes "not decided
 *    yet" and "declined" the same state.
 * 3. **Blockers are shown before the button.** A stale or expired proposal
 *    renders why, with the recompute offer — rather than offering an Accept
 *    that 409s. A button that fails is worse than one that is not there.
 * 4. **`insufficient_data` is not an error.** It is a complete answer whose
 *    remedy is to log more, and rendering it as a failure invites a retry
 *    that cannot help.
 * 5. **No citation UI at all.** There is no curated research library yet, so
 *    there is nothing to cite — and a citation affordance with nothing
 *    behind it is how a fabricated reference gets a box to sit in.
 * 6. **A superseded review still shows what it said.** The chain is the
 *    point: the earlier review was a correct reading of the data it had.
 */
import React, { useEffect, useMemo, useState } from 'react'
import {
  AlertTriangle, Check, ChevronRight, Clock, Info, RefreshCw, X,
} from 'lucide-react'

import {
  useAcceptRecommendation,
  useCoachReview,
  useCoachReviewChain,
  useCoachReviews,
  useRecommendationPreview,
  useRejectRecommendation,
  useRequestReview,
} from '../../hooks/useFitnessCoach'
import type {
  CoachRecommendation,
  CoachReview,
  CoachReviewDetail,
  ConfidenceCategory,
  RecommendationCategory,
  RecommendationPreview,
  ReviewFailureCategory,
  ReviewStatus,
} from '../../types/fitnessCoach'

const CARD = 'rounded-xl border border-white/10 bg-white/[0.03] p-4'
const SECTION = 'text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400'
const SUB = 'text-xs text-slate-400'
const PRIMARY =
  'px-4 py-2 rounded-lg bg-teal-500/90 hover:bg-teal-400 text-slate-950 ' +
  'text-sm font-medium disabled:opacity-40 disabled:cursor-not-allowed'
const DANGER =
  'px-4 py-2 rounded-lg border border-white/15 text-sm text-slate-300 ' +
  'hover:bg-white/[0.06] disabled:opacity-40 disabled:cursor-not-allowed'
const GHOST =
  'px-3 py-1.5 rounded-lg text-sm text-slate-400 hover:text-slate-200 ' +
  'hover:bg-white/[0.04] disabled:opacity-40'

const STATUS_LABEL: Record<ReviewStatus, string> = {
  pending: 'Queued',
  running: 'Thinking…',
  complete: 'Ready',
  failed: 'Could not finish',
  insufficient_data: 'Not enough data yet',
}

/**
 * Plain language, and never "error" for `insufficient_data`.
 *
 * The remedy differs: a model outage is worth retrying, and a week with no
 * logs is not — a retry there burns a minute on the same answer.
 */
const FAILURE_TEXT: Record<ReviewFailureCategory, string> = {
  model_unavailable: 'The local model was unreachable. Worth trying again.',
  model_timeout: 'The model took too long. Worth trying again.',
  invalid_output:
    'The model did not produce something I could check, twice. Nothing has ' +
    'been saved — trying again may work.',
  schema_violation:
    'The model’s answer did not fit the required shape. Nothing was saved.',
  ungrounded_claim:
    'The model cited a number that is not in your data, so the review was ' +
    'rejected rather than shown to you.',
  safety_refused:
    'The model’s answer crossed a line it is not allowed to cross — naming a ' +
    'medical condition, giving treatment advice, or citing research it does ' +
    'not have. It was rejected rather than shown to you.',
  state_unavailable: 'Your data could not be read. This is a fault on our side.',
  insufficient_data:
    'There is not enough logged yet for a review to say anything useful. ' +
    'Log a few more days and ask again.',
  internal_error: 'Something went wrong on our side. Nothing was saved.',
}

const CATEGORY_LABEL: Record<RecommendationCategory, string> = {
  maintain: 'Hold course',
  progress: 'Progress',
  reduce: 'Pull back',
  exercise_change: 'Exercise change',
  volume_change: 'Volume change',
  nutrition_change: 'Nutrition change',
  prioritize_recovery: 'Recovery',
  request_data: 'More data needed',
  flag_concern: 'Worth attention',
}

const CONFIDENCE_LABEL: Record<ConfidenceCategory, string> = {
  low: 'low confidence',
  moderate: 'moderate confidence',
  high: 'high confidence',
}

function StatusPill({ status }: { status: ReviewStatus }) {
  const tone =
    status === 'complete' ? 'text-teal-300 border-teal-400/40 bg-teal-400/[0.08]'
      : status === 'failed' ? 'text-amber-300 border-amber-400/40 bg-amber-400/[0.08]'
      : status === 'insufficient_data'
        ? 'text-slate-300 border-white/15 bg-white/[0.04]'
        : 'text-sky-300 border-sky-400/40 bg-sky-400/[0.08]'
  return (
    <span
      className={`text-[11px] px-2 py-0.5 rounded-full border ${tone}`}
      data-testid="review-status"
      data-status={status}
    >
      {STATUS_LABEL[status]}
    </span>
  )
}

function ReviewRow({
  review, selected, onSelect,
}: {
  review: CoachReview
  selected: boolean
  onSelect: () => void
}) {
  return (
    <button
      onClick={onSelect}
      aria-current={selected ? 'true' : undefined}
      data-testid={`review-row-${review.id}`}
      className={`w-full text-left px-3 py-2.5 rounded-lg border transition-colors ${
        selected
          ? 'border-teal-400/40 bg-teal-400/[0.06]'
          : 'border-white/10 hover:bg-white/[0.04]'
      }`}
    >
      <div className="flex items-center justify-between gap-2">
        <span className="text-sm text-slate-200">
          {review.period.start} → {review.period.end}
        </span>
        <StatusPill status={review.status} />
      </div>
      <div className="flex items-center gap-2 mt-1">
        <span className="text-[11px] text-slate-500 capitalize">
          {review.kind.replace(/_/g, ' ')}
        </span>
        {review.revision > 1 ? (
          <span className="text-[11px] text-slate-500" data-testid="revision-badge">
            · revision {review.revision}
          </span>
        ) : null}
        {review.superseded_by_id ? (
          <span className="text-[11px] text-amber-300/80" data-testid="superseded-badge">
            · superseded
          </span>
        ) : null}
      </div>
    </button>
  )
}

function Coverage({ review }: { review: CoachReviewDetail }) {
  const quality = review.input_state?.quality
  if (!quality) return null
  return (
    <div className={CARD} data-testid="coverage">
      <span className={SECTION}>What this is built from</span>
      <dl className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-sm">
        <dt className="text-slate-400">Weigh-ins</dt>
        <dd className="text-slate-200 tabular-nums">
          {quality.observed_weight_days ?? 0} of{' '}
          {quality.expected_weight_days ?? 0} days
        </dd>
        <dt className="text-slate-400">Fully logged food</dt>
        <dd className="text-slate-200 tabular-nums">
          {quality.nutrition_complete_days} days
        </dd>
        <dt className="text-slate-400">Partly logged</dt>
        <dd className="text-slate-200 tabular-nums">
          {quality.nutrition_partial_days} days
        </dd>
        <dt className="text-slate-400">Sleep recorded</dt>
        <dd className="text-slate-200 tabular-nums">
          {quality.sleep_nights ?? 0} nights
        </dd>
      </dl>
      {quality.missing_fields.length > 0 ? (
        <details className="mt-3" data-testid="unavailable-list">
          <summary className="cursor-pointer text-xs text-slate-400">
            {quality.missing_fields.length} things this review could not know
          </summary>
          <ul className="mt-2 flex flex-col gap-1">
            {quality.missing_fields.map((field) => {
              const [name, reason] = field.split(': ')
              return (
                <li key={field} className="text-[11px] text-slate-500">
                  <span className="text-slate-400">{name}</span> —{' '}
                  {(reason ?? '').replace(/_/g, ' ')}
                </li>
              )
            })}
          </ul>
        </details>
      ) : null}
    </div>
  )
}

/**
 * The observations, with the exact figures they cited.
 *
 * Read from the FROZEN snapshot, not recomputed: the point is what the
 * review reasoned from, and a recomputed number would quietly answer a
 * different question (what it would say today).
 */
function Observations({ review }: { review: CoachReviewDetail }) {
  const metrics = useMemo(() => {
    const out: Record<string, { value: number | null; unit: string; coverage: string | null; reason: string | null }> = {}
    const sections = review.input_state?.sections ?? {}
    for (const [sectionName, group] of Object.entries(sections)) {
      for (const [key, metric] of Object.entries(group?.metrics ?? {})) {
        out[`${sectionName}.${key}`] = {
          value: metric.value,
          unit: metric.unit,
          coverage:
            metric.observed_days != null && metric.expected_days != null
              ? `${metric.observed_days} of ${metric.expected_days} days`
              : null,
          reason: metric.unavailable_reason ?? null,
        }
      }
    }
    return out
  }, [review])

  const observations = review.output?.observations ?? []
  if (observations.length === 0) return null

  return (
    <div className={CARD} data-testid="observations">
      <span className={SECTION}>What it noticed</span>
      <ul className="mt-2 flex flex-col gap-3">
        {observations.map((observation, index) => (
          <li key={index} className="text-sm text-slate-200">
            {observation.text}
            {observation.metric_paths.length > 0 ? (
              <ul className="mt-1 flex flex-wrap gap-2">
                {observation.metric_paths.map((path) => {
                  const metric = metrics[path]
                  return (
                    <li
                      key={path}
                      className="text-[11px] px-2 py-0.5 rounded border border-white/10 text-slate-400"
                      data-testid={`cited-${path}`}
                    >
                      {path.replace(/_/g, ' ')}
                      {metric
                        ? metric.value != null
                          ? `: ${metric.value} ${metric.unit}${
                              metric.coverage ? ` · ${metric.coverage}` : ''
                            }`
                          : `: unknown (${(metric.reason ?? '').replace(/_/g, ' ')})`
                        : ': not in the snapshot'}
                    </li>
                  )
                })}
              </ul>
            ) : null}
          </li>
        ))}
      </ul>
    </div>
  )
}

function ChangeTable({ preview }: { preview: RecommendationPreview }) {
  const changed = preview.changes.filter((change) => change.is_change)
  if (preview.changes.length === 0) {
    return (
      <p className={SUB} data-testid="no-change">
        Accepting this records that you agree. It changes no numbers.
      </p>
    )
  }
  return (
    <table className="w-full text-sm mt-2" data-testid="change-table">
      <thead>
        <tr className="text-[11px] uppercase tracking-wider text-slate-500">
          <th className="text-left font-medium pb-1">Field</th>
          <th className="text-right font-medium pb-1">Now</th>
          <th className="text-right font-medium pb-1">Proposed</th>
        </tr>
      </thead>
      <tbody>
        {preview.changes.map((change) => (
          <tr
            key={change.field}
            data-testid={`change-${change.field}`}
            className={change.is_change ? 'text-slate-100' : 'text-slate-500'}
          >
            <td className="py-0.5">{change.field.replace(/_/g, ' ')}</td>
            <td className="text-right tabular-nums py-0.5">
              {change.current ?? '—'}
            </td>
            <td className="text-right tabular-nums py-0.5">
              {change.proposed ?? '—'}
              {change.delta != null && change.delta !== 0 ? (
                <span className="text-[11px] text-slate-400 ml-1">
                  ({change.delta > 0 ? '+' : ''}{change.delta})
                </span>
              ) : null}
            </td>
          </tr>
        ))}
      </tbody>
      {changed.length === 0 ? (
        <tfoot>
          <tr>
            <td colSpan={3} className="text-[11px] text-amber-300/80 pt-1">
              Nothing here differs from your current targets.
            </td>
          </tr>
        </tfoot>
      ) : null}
    </table>
  )
}

function RecommendationCard({
  recommendation, onDecided,
}: {
  recommendation: CoachRecommendation
  onDecided: (message: string) => void
}) {
  const [expanded, setExpanded] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const previewQuery = useRecommendationPreview(
    expanded ? recommendation.id : undefined,
  )
  const accept = useAcceptRecommendation()
  const reject = useRejectRecommendation()
  const preview = previewQuery.data

  const decided = recommendation.decision_status !== 'proposed'

  const handleAccept = async () => {
    setError(null)
    try {
      const result = await accept.mutateAsync({
        recommendationId: recommendation.id,
      })
      onDecided(result.message)
    } catch (caught) {
      const message =
        caught instanceof Error ? caught.message : 'Could not apply that.'
      setError(message)
      // A stale proposal invalidates its own preview, so reopening shows the
      // blocker instead of the Accept button again.
      previewQuery.refetch()
    }
  }

  const handleReject = async () => {
    setError(null)
    try {
      await reject.mutateAsync({ recommendationId: recommendation.id })
      onDecided('Noted — nothing changed.')
    } catch (caught) {
      setError(
        caught instanceof Error ? caught.message : 'Could not record that.',
      )
    }
  }

  return (
    <div className={CARD} data-testid={`recommendation-${recommendation.id}`}>
      <div className="flex items-start justify-between gap-3">
        <div>
          <span
            className="text-[11px] px-2 py-0.5 rounded-full border border-white/15 text-slate-400"
            data-testid="rec-category"
          >
            {CATEGORY_LABEL[recommendation.category]}
          </span>
          <h4 className="text-sm text-slate-100 mt-1.5">{recommendation.title}</h4>
        </div>
        {decided ? (
          <span
            className="text-[11px] text-slate-400 whitespace-nowrap"
            data-testid="rec-decision"
            data-decision={recommendation.decision_status}
          >
            {recommendation.decision_status}
          </span>
        ) : null}
      </div>

      <p className="text-sm text-slate-300 mt-2">{recommendation.rationale}</p>

      {/* Confidence and coverage, side by side and labelled as different
          things. A confident reading of three days is still three days. */}
      <p className="text-[11px] text-slate-500 mt-2" data-testid="rec-confidence">
        {CONFIDENCE_LABEL[recommendation.confidence]}
        {recommendation.confidence_basis
          ? ` — ${recommendation.confidence_basis}`
          : ''}
      </p>
      {recommendation.limitations ? (
        <p className="text-[11px] text-slate-500 mt-1" data-testid="rec-limitations">
          {recommendation.limitations}
        </p>
      ) : null}

      {decided ? (
        <div className="mt-3 pt-3 border-t border-white/[0.06] text-xs text-slate-400">
          {recommendation.decision_status === 'accepted' ? (
            <span data-testid="rec-receipt">
              Applied
              {recommendation.applied_revision_id
                ? ` as target revision ${recommendation.applied_revision_id.slice(0, 8)}`
                : ''}
              {recommendation.decided_at
                ? ` on ${recommendation.decided_at.slice(0, 10)}`
                : ''}
              . Receipt {(recommendation.action_receipt_id ?? '').slice(0, 8)}.
            </span>
          ) : (
            <span>
              {recommendation.decision_status} on{' '}
              {(recommendation.decided_at ?? '').slice(0, 10)}
              {recommendation.decision_note
                ? ` — ${recommendation.decision_note}`
                : ''}
            </span>
          )}
        </div>
      ) : (
        <div className="mt-3 pt-3 border-t border-white/[0.06]">
          {!expanded ? (
            <button
              className={GHOST}
              onClick={() => setExpanded(true)}
              data-testid="rec-expand"
            >
              See exactly what this would change
              <ChevronRight className="w-3.5 h-3.5 inline ml-1" />
            </button>
          ) : previewQuery.isLoading ? (
            <p className={SUB}>Checking what this would change…</p>
          ) : previewQuery.isError || !preview ? (
            <p className="text-xs text-amber-300/90" data-testid="preview-error">
              Could not check what this would change, so there is no Accept
              button. Nothing has happened.
            </p>
          ) : (
            <>
              <div className="flex items-baseline justify-between gap-2">
                <span className={SECTION}>If you accept</span>
                {preview.effective_date ? (
                  <span className="text-[11px] text-slate-500" data-testid="effective-date">
                    from {preview.effective_date}
                    {preview.scope ? ` · ${preview.scope} scope` : ''}
                  </span>
                ) : null}
              </div>
              <ChangeTable preview={preview} />

              {/* Blockers BEFORE the button, not discovered by pressing it. */}
              {preview.blockers.length > 0 ? (
                <div
                  className="mt-3 flex items-start gap-2 text-xs text-amber-200/90"
                  data-testid="rec-blockers"
                  role="status"
                >
                  <AlertTriangle className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" />
                  <div>
                    <ul className="flex flex-col gap-1">
                      {preview.blockers.map((blocker) => (
                        <li key={blocker}>{blocker}</li>
                      ))}
                    </ul>
                    {preview.stale || preview.expired ? (
                      <p className="mt-1 text-slate-400">
                        Ask for a new review of the current period and decide
                        on that instead.
                      </p>
                    ) : null}
                    {!preview.applicable ? (
                      <p className="mt-1 text-slate-400" data-testid="advice-only">
                        This stays as advice. Make the change yourself in the
                        plan editor if you agree with it.
                      </p>
                    ) : null}
                  </div>
                </div>
              ) : null}

              <div className="flex items-center gap-2 mt-3">
                <button
                  className={PRIMARY}
                  onClick={handleAccept}
                  disabled={!preview.acceptable || accept.isPending}
                  data-testid="rec-accept"
                >
                  {accept.isPending ? 'Applying…' : 'Accept'}
                </button>
                <button
                  className={DANGER}
                  onClick={handleReject}
                  disabled={reject.isPending}
                  data-testid="rec-reject"
                >
                  {reject.isPending ? 'Saving…' : 'Reject'}
                </button>
                <button className={GHOST} onClick={() => setExpanded(false)}>
                  Later
                </button>
              </div>
            </>
          )}
          {error ? (
            <p className="mt-2 text-xs text-amber-300/90" data-testid="rec-error">
              {error}
            </p>
          ) : null}
        </div>
      )}
    </div>
  )
}

function ReviewDetail({
  reviewId, onDecided,
}: {
  reviewId: string
  onDecided: (message: string) => void
}) {
  const reviewQuery = useCoachReview(reviewId, { withState: true })
  const chainQuery = useCoachReviewChain(reviewId)
  const review = reviewQuery.data

  if (reviewQuery.isLoading) {
    return (
      <div className="flex items-center gap-2 text-sm text-slate-400 py-8">
        <RefreshCw className="w-4 h-4 animate-spin" />
        Loading the review…
      </div>
    )
  }
  if (reviewQuery.isError || !review) {
    return (
      <div className={CARD} data-testid="detail-error" role="alert">
        <p className="text-sm text-amber-200/90">
          Could not load that review. This is a read failure, not a lost
          review — nothing has been deleted.
        </p>
      </div>
    )
  }

  if (review.status === 'pending' || review.status === 'running') {
    return (
      <div className={CARD} data-testid="review-in-flight">
        <div className="flex items-center gap-2 text-sm text-slate-300">
          <RefreshCw className="w-4 h-4 animate-spin" />
          {review.status === 'pending'
            ? 'Queued — waiting for a worker.'
            : 'Thinking. This takes about a minute on the local model.'}
        </div>
        <p className={`${SUB} mt-2`}>
          {review.period.start} → {review.period.end}. Nothing about your plan
          changes while this runs.
        </p>
      </div>
    )
  }

  if (review.status === 'insufficient_data') {
    return (
      <div className={CARD} data-testid="review-insufficient">
        <span className={SECTION}>Not enough data yet</span>
        <p className="text-sm text-slate-200 mt-2">
          {FAILURE_TEXT.insufficient_data}
        </p>
        {review.error_detail ? (
          <p className={`${SUB} mt-2`} data-testid="insufficient-detail">
            {review.error_detail}
          </p>
        ) : null}
        <p className="text-[11px] text-slate-500 mt-3">
          This is a complete answer, not a failure — trying again without
          logging more would give the same one.
        </p>
      </div>
    )
  }

  if (review.status === 'failed') {
    return (
      <div className={CARD} data-testid="review-failed" role="alert">
        <span className={SECTION}>Could not finish</span>
        <p className="text-sm text-amber-200/90 mt-2">
          {review.error_category
            ? FAILURE_TEXT[review.error_category]
            : 'Something went wrong. Nothing was saved.'}
        </p>
        <p className="text-[11px] text-slate-500 mt-3">
          Nothing about your plan changed, and none of your logged data was
          touched.
        </p>
      </div>
    )
  }

  const chain = chainQuery.data ?? []

  return (
    <div className="flex flex-col gap-4" data-testid="review-detail">
      <div className={CARD}>
        <div className="flex items-baseline justify-between gap-2">
          <span className={SECTION}>
            {review.period.start} → {review.period.end}
          </span>
          <span className="text-[11px] text-slate-500" data-testid="review-meta">
            {review.model_actual ?? 'unknown model'} ·{' '}
            {review.prompt_version} · analytics v{review.analytics_version}
          </span>
        </div>
        <p className="text-sm text-slate-100 mt-2">{review.output?.summary}</p>
        {review.output?.coaching_priority ? (
          <p className="text-sm text-teal-200/90 mt-2" data-testid="priority">
            {review.output.coaching_priority}
          </p>
        ) : null}
        <p className="text-[11px] text-slate-500 mt-2" data-testid="review-confidence">
          {review.output
            ? `${CONFIDENCE_LABEL[review.output.confidence]} — ${review.output.confidence_basis}`
            : ''}
        </p>
        {review.superseded_by_id ? (
          <p className="text-[11px] text-amber-300/80 mt-2" data-testid="superseded-note">
            A newer revision of this review exists. This one is kept because it
            was a correct reading of the data it had.
          </p>
        ) : null}
      </div>

      {review.output && review.output.limitations.length > 0 ? (
        <div className={CARD} data-testid="limitations">
          <span className={SECTION}>What this cannot tell you</span>
          <ul className="mt-2 flex flex-col gap-1">
            {review.output.limitations.map((limitation) => (
              <li key={limitation} className="text-sm text-slate-300">
                {limitation}
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      <Observations review={review} />
      <Coverage review={review} />

      {review.recommendations.length > 0 ? (
        <div className="flex flex-col gap-3">
          <span className={SECTION}>Decide</span>
          {review.recommendations.map((recommendation) => (
            <RecommendationCard
              key={recommendation.id}
              recommendation={recommendation}
              onDecided={onDecided}
            />
          ))}
        </div>
      ) : (
        <p className={SUB} data-testid="no-recommendations">
          Nothing to decide on from this one.
        </p>
      )}

      {chain.length > 1 ? (
        <details className={CARD} data-testid="review-chain">
          <summary className="cursor-pointer text-xs text-slate-400">
            {chain.length} revisions of this review
          </summary>
          <ul className="mt-2 flex flex-col gap-1">
            {chain.map((revision) => (
              <li key={revision.id} className="text-[11px] text-slate-500">
                revision {revision.revision} · {STATUS_LABEL[revision.status]}
                {revision.id === review.id ? ' · showing this one' : ''}
              </li>
            ))}
          </ul>
        </details>
      ) : null}
    </div>
  )
}

export default function CoachReviews() {
  const reviewsQuery = useCoachReviews({ limit: 20 })
  const requestReview = useRequestReview()
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [banner, setBanner] = useState<string | null>(null)
  const [requestError, setRequestError] = useState<string | null>(null)

  const reviews = reviewsQuery.data ?? []

  // Select the newest review once, when the list first arrives. Not on every
  // change: re-selecting would yank the pane out from under someone reading
  // an older review while a new one finishes.
  useEffect(() => {
    if (selectedId === null && reviews.length > 0) {
      setSelectedId(reviews[0].id)
    }
  }, [reviews, selectedId])

  const handleRequest = async (force = false) => {
    setRequestError(null)
    setBanner(null)
    try {
      const review = await requestReview.mutateAsync({ kind: 'weekly', force })
      setSelectedId(review.id)
    } catch (caught) {
      const message =
        caught instanceof Error ? caught.message : 'Could not start a review.'
      setRequestError(message)
    }
  }

  return (
    <div className="flex flex-col gap-4" data-testid="coach-reviews">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h2 className="text-sm font-semibold text-slate-200">Coach reviews</h2>
          <p className={`${SUB} mt-0.5`}>
            A review reads your logged data and proposes changes. Nothing
            changes until you accept something.
          </p>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <button
            className={PRIMARY}
            onClick={() => handleRequest(false)}
            disabled={requestReview.isPending}
            data-testid="request-review"
          >
            {requestReview.isPending ? 'Starting…' : 'Review this week'}
          </button>
        </div>
      </div>

      {banner ? (
        <div
          className="rounded-xl border border-teal-400/30 bg-teal-400/[0.06] p-3 flex items-start gap-2"
          data-testid="decision-banner"
          role="status"
        >
          <Check className="w-4 h-4 text-teal-300 mt-0.5 flex-shrink-0" />
          <p className="text-xs text-teal-100/90">{banner}</p>
          <button
            className="ml-auto text-slate-400 hover:text-slate-200"
            onClick={() => setBanner(null)}
            aria-label="Dismiss"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      ) : null}

      {requestError ? (
        <div
          className="rounded-xl border border-amber-400/40 bg-amber-400/[0.06] p-3"
          data-testid="request-error"
          role="alert"
        >
          <p className="text-xs text-amber-200/90">{requestError}</p>
          {/* A review of this period already exists with different data
              behind it. Forcing produces a linked revision and keeps the old
              one, so this is an offer rather than an overwrite. */}
          {requestError.toLowerCase().includes('force') ? (
            <button
              className={`${GHOST} mt-2`}
              onClick={() => handleRequest(true)}
              data-testid="force-review"
            >
              Run it again on the current data (keeps the old review)
            </button>
          ) : null}
        </div>
      ) : null}

      <div className="grid gap-4 lg:grid-cols-[minmax(0,18rem)_1fr]">
        <div className="flex flex-col gap-2" data-testid="review-list">
          {reviewsQuery.isLoading ? (
            <p className={SUB}>Loading…</p>
          ) : reviews.length === 0 ? (
            <div className={CARD} data-testid="no-reviews">
              <p className="text-sm text-slate-300">No reviews yet.</p>
              <p className={`${SUB} mt-1`}>
                Reviews are only produced when you ask for one, or on a
                schedule you turn on yourself.
              </p>
            </div>
          ) : (
            reviews.map((review) => (
              <ReviewRow
                key={review.id}
                review={review}
                selected={review.id === selectedId}
                onSelect={() => setSelectedId(review.id)}
              />
            ))
          )}
        </div>

        <div>
          {selectedId ? (
            <ReviewDetail
              reviewId={selectedId}
              onDecided={(message) => setBanner(message)}
            />
          ) : (
            <div className={CARD}>
              <p className={SUB}>
                Pick a review on the left, or ask for one.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
